
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Archivo` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Archivo
 * 
 */
export type ArchivoModel = runtime.Types.Result.DefaultSelection<Prisma.$ArchivoPayload>

export type AggregateArchivo = {
  _count: ArchivoCountAggregateOutputType | null
  _min: ArchivoMinAggregateOutputType | null
  _max: ArchivoMaxAggregateOutputType | null
}

export type ArchivoMinAggregateOutputType = {
  id: string | null
  projectId: string | null
  kind: $Enums.ArchivoKind | null
  title: string | null
  path: string | null
  mimeType: string | null
  driveFileId: string | null
  sourceNotaId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ArchivoMaxAggregateOutputType = {
  id: string | null
  projectId: string | null
  kind: $Enums.ArchivoKind | null
  title: string | null
  path: string | null
  mimeType: string | null
  driveFileId: string | null
  sourceNotaId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ArchivoCountAggregateOutputType = {
  id: number
  projectId: number
  kind: number
  title: number
  path: number
  mimeType: number
  driveFileId: number
  sourceNotaId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ArchivoMinAggregateInputType = {
  id?: true
  projectId?: true
  kind?: true
  title?: true
  path?: true
  mimeType?: true
  driveFileId?: true
  sourceNotaId?: true
  createdAt?: true
  updatedAt?: true
}

export type ArchivoMaxAggregateInputType = {
  id?: true
  projectId?: true
  kind?: true
  title?: true
  path?: true
  mimeType?: true
  driveFileId?: true
  sourceNotaId?: true
  createdAt?: true
  updatedAt?: true
}

export type ArchivoCountAggregateInputType = {
  id?: true
  projectId?: true
  kind?: true
  title?: true
  path?: true
  mimeType?: true
  driveFileId?: true
  sourceNotaId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ArchivoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Archivo to aggregate.
   */
  where?: Prisma.ArchivoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Archivos to fetch.
   */
  orderBy?: Prisma.ArchivoOrderByWithRelationInput | Prisma.ArchivoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ArchivoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Archivos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Archivos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Archivos
  **/
  _count?: true | ArchivoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ArchivoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ArchivoMaxAggregateInputType
}

export type GetArchivoAggregateType<T extends ArchivoAggregateArgs> = {
      [P in keyof T & keyof AggregateArchivo]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateArchivo[P]>
    : Prisma.GetScalarType<T[P], AggregateArchivo[P]>
}




export type ArchivoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ArchivoWhereInput
  orderBy?: Prisma.ArchivoOrderByWithAggregationInput | Prisma.ArchivoOrderByWithAggregationInput[]
  by: Prisma.ArchivoScalarFieldEnum[] | Prisma.ArchivoScalarFieldEnum
  having?: Prisma.ArchivoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ArchivoCountAggregateInputType | true
  _min?: ArchivoMinAggregateInputType
  _max?: ArchivoMaxAggregateInputType
}

export type ArchivoGroupByOutputType = {
  id: string
  projectId: string
  kind: $Enums.ArchivoKind
  title: string
  path: string
  mimeType: string | null
  driveFileId: string | null
  sourceNotaId: string | null
  createdAt: Date
  updatedAt: Date
  _count: ArchivoCountAggregateOutputType | null
  _min: ArchivoMinAggregateOutputType | null
  _max: ArchivoMaxAggregateOutputType | null
}

export type GetArchivoGroupByPayload<T extends ArchivoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ArchivoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ArchivoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ArchivoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ArchivoGroupByOutputType[P]>
      }
    >
  >



export type ArchivoWhereInput = {
  AND?: Prisma.ArchivoWhereInput | Prisma.ArchivoWhereInput[]
  OR?: Prisma.ArchivoWhereInput[]
  NOT?: Prisma.ArchivoWhereInput | Prisma.ArchivoWhereInput[]
  id?: Prisma.StringFilter<"Archivo"> | string
  projectId?: Prisma.StringFilter<"Archivo"> | string
  kind?: Prisma.EnumArchivoKindFilter<"Archivo"> | $Enums.ArchivoKind
  title?: Prisma.StringFilter<"Archivo"> | string
  path?: Prisma.StringFilter<"Archivo"> | string
  mimeType?: Prisma.StringNullableFilter<"Archivo"> | string | null
  driveFileId?: Prisma.StringNullableFilter<"Archivo"> | string | null
  sourceNotaId?: Prisma.StringNullableFilter<"Archivo"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Archivo"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Archivo"> | Date | string
  project?: Prisma.XOR<Prisma.ProyectoScalarRelationFilter, Prisma.ProyectoWhereInput>
}

export type ArchivoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  title?: Prisma.SortOrder
  path?: Prisma.SortOrder
  mimeType?: Prisma.SortOrderInput | Prisma.SortOrder
  driveFileId?: Prisma.SortOrderInput | Prisma.SortOrder
  sourceNotaId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  project?: Prisma.ProyectoOrderByWithRelationInput
}

export type ArchivoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  sourceNotaId?: string
  AND?: Prisma.ArchivoWhereInput | Prisma.ArchivoWhereInput[]
  OR?: Prisma.ArchivoWhereInput[]
  NOT?: Prisma.ArchivoWhereInput | Prisma.ArchivoWhereInput[]
  projectId?: Prisma.StringFilter<"Archivo"> | string
  kind?: Prisma.EnumArchivoKindFilter<"Archivo"> | $Enums.ArchivoKind
  title?: Prisma.StringFilter<"Archivo"> | string
  path?: Prisma.StringFilter<"Archivo"> | string
  mimeType?: Prisma.StringNullableFilter<"Archivo"> | string | null
  driveFileId?: Prisma.StringNullableFilter<"Archivo"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Archivo"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Archivo"> | Date | string
  project?: Prisma.XOR<Prisma.ProyectoScalarRelationFilter, Prisma.ProyectoWhereInput>
}, "id" | "sourceNotaId">

export type ArchivoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  title?: Prisma.SortOrder
  path?: Prisma.SortOrder
  mimeType?: Prisma.SortOrderInput | Prisma.SortOrder
  driveFileId?: Prisma.SortOrderInput | Prisma.SortOrder
  sourceNotaId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ArchivoCountOrderByAggregateInput
  _max?: Prisma.ArchivoMaxOrderByAggregateInput
  _min?: Prisma.ArchivoMinOrderByAggregateInput
}

export type ArchivoScalarWhereWithAggregatesInput = {
  AND?: Prisma.ArchivoScalarWhereWithAggregatesInput | Prisma.ArchivoScalarWhereWithAggregatesInput[]
  OR?: Prisma.ArchivoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ArchivoScalarWhereWithAggregatesInput | Prisma.ArchivoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Archivo"> | string
  projectId?: Prisma.StringWithAggregatesFilter<"Archivo"> | string
  kind?: Prisma.EnumArchivoKindWithAggregatesFilter<"Archivo"> | $Enums.ArchivoKind
  title?: Prisma.StringWithAggregatesFilter<"Archivo"> | string
  path?: Prisma.StringWithAggregatesFilter<"Archivo"> | string
  mimeType?: Prisma.StringNullableWithAggregatesFilter<"Archivo"> | string | null
  driveFileId?: Prisma.StringNullableWithAggregatesFilter<"Archivo"> | string | null
  sourceNotaId?: Prisma.StringNullableWithAggregatesFilter<"Archivo"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Archivo"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Archivo"> | Date | string
}

export type ArchivoCreateInput = {
  id?: string
  kind: $Enums.ArchivoKind
  title: string
  path: string
  mimeType?: string | null
  driveFileId?: string | null
  sourceNotaId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  project: Prisma.ProyectoCreateNestedOneWithoutArchivosInput
}

export type ArchivoUncheckedCreateInput = {
  id?: string
  projectId: string
  kind: $Enums.ArchivoKind
  title: string
  path: string
  mimeType?: string | null
  driveFileId?: string | null
  sourceNotaId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ArchivoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumArchivoKindFieldUpdateOperationsInput | $Enums.ArchivoKind
  title?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driveFileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourceNotaId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProyectoUpdateOneRequiredWithoutArchivosNestedInput
}

export type ArchivoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumArchivoKindFieldUpdateOperationsInput | $Enums.ArchivoKind
  title?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driveFileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourceNotaId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ArchivoCreateManyInput = {
  id?: string
  projectId: string
  kind: $Enums.ArchivoKind
  title: string
  path: string
  mimeType?: string | null
  driveFileId?: string | null
  sourceNotaId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ArchivoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumArchivoKindFieldUpdateOperationsInput | $Enums.ArchivoKind
  title?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driveFileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourceNotaId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ArchivoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumArchivoKindFieldUpdateOperationsInput | $Enums.ArchivoKind
  title?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driveFileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourceNotaId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ArchivoListRelationFilter = {
  every?: Prisma.ArchivoWhereInput
  some?: Prisma.ArchivoWhereInput
  none?: Prisma.ArchivoWhereInput
}

export type ArchivoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ArchivoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  title?: Prisma.SortOrder
  path?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  driveFileId?: Prisma.SortOrder
  sourceNotaId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ArchivoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  title?: Prisma.SortOrder
  path?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  driveFileId?: Prisma.SortOrder
  sourceNotaId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ArchivoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  kind?: Prisma.SortOrder
  title?: Prisma.SortOrder
  path?: Prisma.SortOrder
  mimeType?: Prisma.SortOrder
  driveFileId?: Prisma.SortOrder
  sourceNotaId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ArchivoCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.ArchivoCreateWithoutProjectInput, Prisma.ArchivoUncheckedCreateWithoutProjectInput> | Prisma.ArchivoCreateWithoutProjectInput[] | Prisma.ArchivoUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ArchivoCreateOrConnectWithoutProjectInput | Prisma.ArchivoCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.ArchivoCreateManyProjectInputEnvelope
  connect?: Prisma.ArchivoWhereUniqueInput | Prisma.ArchivoWhereUniqueInput[]
}

export type ArchivoUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.ArchivoCreateWithoutProjectInput, Prisma.ArchivoUncheckedCreateWithoutProjectInput> | Prisma.ArchivoCreateWithoutProjectInput[] | Prisma.ArchivoUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ArchivoCreateOrConnectWithoutProjectInput | Prisma.ArchivoCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.ArchivoCreateManyProjectInputEnvelope
  connect?: Prisma.ArchivoWhereUniqueInput | Prisma.ArchivoWhereUniqueInput[]
}

export type ArchivoUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.ArchivoCreateWithoutProjectInput, Prisma.ArchivoUncheckedCreateWithoutProjectInput> | Prisma.ArchivoCreateWithoutProjectInput[] | Prisma.ArchivoUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ArchivoCreateOrConnectWithoutProjectInput | Prisma.ArchivoCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.ArchivoUpsertWithWhereUniqueWithoutProjectInput | Prisma.ArchivoUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.ArchivoCreateManyProjectInputEnvelope
  set?: Prisma.ArchivoWhereUniqueInput | Prisma.ArchivoWhereUniqueInput[]
  disconnect?: Prisma.ArchivoWhereUniqueInput | Prisma.ArchivoWhereUniqueInput[]
  delete?: Prisma.ArchivoWhereUniqueInput | Prisma.ArchivoWhereUniqueInput[]
  connect?: Prisma.ArchivoWhereUniqueInput | Prisma.ArchivoWhereUniqueInput[]
  update?: Prisma.ArchivoUpdateWithWhereUniqueWithoutProjectInput | Prisma.ArchivoUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.ArchivoUpdateManyWithWhereWithoutProjectInput | Prisma.ArchivoUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.ArchivoScalarWhereInput | Prisma.ArchivoScalarWhereInput[]
}

export type ArchivoUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.ArchivoCreateWithoutProjectInput, Prisma.ArchivoUncheckedCreateWithoutProjectInput> | Prisma.ArchivoCreateWithoutProjectInput[] | Prisma.ArchivoUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.ArchivoCreateOrConnectWithoutProjectInput | Prisma.ArchivoCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.ArchivoUpsertWithWhereUniqueWithoutProjectInput | Prisma.ArchivoUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.ArchivoCreateManyProjectInputEnvelope
  set?: Prisma.ArchivoWhereUniqueInput | Prisma.ArchivoWhereUniqueInput[]
  disconnect?: Prisma.ArchivoWhereUniqueInput | Prisma.ArchivoWhereUniqueInput[]
  delete?: Prisma.ArchivoWhereUniqueInput | Prisma.ArchivoWhereUniqueInput[]
  connect?: Prisma.ArchivoWhereUniqueInput | Prisma.ArchivoWhereUniqueInput[]
  update?: Prisma.ArchivoUpdateWithWhereUniqueWithoutProjectInput | Prisma.ArchivoUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.ArchivoUpdateManyWithWhereWithoutProjectInput | Prisma.ArchivoUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.ArchivoScalarWhereInput | Prisma.ArchivoScalarWhereInput[]
}

export type EnumArchivoKindFieldUpdateOperationsInput = {
  set?: $Enums.ArchivoKind
}

export type ArchivoCreateWithoutProjectInput = {
  id?: string
  kind: $Enums.ArchivoKind
  title: string
  path: string
  mimeType?: string | null
  driveFileId?: string | null
  sourceNotaId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ArchivoUncheckedCreateWithoutProjectInput = {
  id?: string
  kind: $Enums.ArchivoKind
  title: string
  path: string
  mimeType?: string | null
  driveFileId?: string | null
  sourceNotaId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ArchivoCreateOrConnectWithoutProjectInput = {
  where: Prisma.ArchivoWhereUniqueInput
  create: Prisma.XOR<Prisma.ArchivoCreateWithoutProjectInput, Prisma.ArchivoUncheckedCreateWithoutProjectInput>
}

export type ArchivoCreateManyProjectInputEnvelope = {
  data: Prisma.ArchivoCreateManyProjectInput | Prisma.ArchivoCreateManyProjectInput[]
}

export type ArchivoUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.ArchivoWhereUniqueInput
  update: Prisma.XOR<Prisma.ArchivoUpdateWithoutProjectInput, Prisma.ArchivoUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.ArchivoCreateWithoutProjectInput, Prisma.ArchivoUncheckedCreateWithoutProjectInput>
}

export type ArchivoUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.ArchivoWhereUniqueInput
  data: Prisma.XOR<Prisma.ArchivoUpdateWithoutProjectInput, Prisma.ArchivoUncheckedUpdateWithoutProjectInput>
}

export type ArchivoUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.ArchivoScalarWhereInput
  data: Prisma.XOR<Prisma.ArchivoUpdateManyMutationInput, Prisma.ArchivoUncheckedUpdateManyWithoutProjectInput>
}

export type ArchivoScalarWhereInput = {
  AND?: Prisma.ArchivoScalarWhereInput | Prisma.ArchivoScalarWhereInput[]
  OR?: Prisma.ArchivoScalarWhereInput[]
  NOT?: Prisma.ArchivoScalarWhereInput | Prisma.ArchivoScalarWhereInput[]
  id?: Prisma.StringFilter<"Archivo"> | string
  projectId?: Prisma.StringFilter<"Archivo"> | string
  kind?: Prisma.EnumArchivoKindFilter<"Archivo"> | $Enums.ArchivoKind
  title?: Prisma.StringFilter<"Archivo"> | string
  path?: Prisma.StringFilter<"Archivo"> | string
  mimeType?: Prisma.StringNullableFilter<"Archivo"> | string | null
  driveFileId?: Prisma.StringNullableFilter<"Archivo"> | string | null
  sourceNotaId?: Prisma.StringNullableFilter<"Archivo"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Archivo"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Archivo"> | Date | string
}

export type ArchivoCreateManyProjectInput = {
  id?: string
  kind: $Enums.ArchivoKind
  title: string
  path: string
  mimeType?: string | null
  driveFileId?: string | null
  sourceNotaId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ArchivoUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumArchivoKindFieldUpdateOperationsInput | $Enums.ArchivoKind
  title?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driveFileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourceNotaId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ArchivoUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumArchivoKindFieldUpdateOperationsInput | $Enums.ArchivoKind
  title?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driveFileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourceNotaId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ArchivoUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  kind?: Prisma.EnumArchivoKindFieldUpdateOperationsInput | $Enums.ArchivoKind
  title?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  mimeType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driveFileId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourceNotaId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ArchivoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  kind?: boolean
  title?: boolean
  path?: boolean
  mimeType?: boolean
  driveFileId?: boolean
  sourceNotaId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  project?: boolean | Prisma.ProyectoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["archivo"]>

export type ArchivoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  kind?: boolean
  title?: boolean
  path?: boolean
  mimeType?: boolean
  driveFileId?: boolean
  sourceNotaId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  project?: boolean | Prisma.ProyectoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["archivo"]>

export type ArchivoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  kind?: boolean
  title?: boolean
  path?: boolean
  mimeType?: boolean
  driveFileId?: boolean
  sourceNotaId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  project?: boolean | Prisma.ProyectoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["archivo"]>

export type ArchivoSelectScalar = {
  id?: boolean
  projectId?: boolean
  kind?: boolean
  title?: boolean
  path?: boolean
  mimeType?: boolean
  driveFileId?: boolean
  sourceNotaId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ArchivoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "projectId" | "kind" | "title" | "path" | "mimeType" | "driveFileId" | "sourceNotaId" | "createdAt" | "updatedAt", ExtArgs["result"]["archivo"]>
export type ArchivoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProyectoDefaultArgs<ExtArgs>
}
export type ArchivoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProyectoDefaultArgs<ExtArgs>
}
export type ArchivoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProyectoDefaultArgs<ExtArgs>
}

export type $ArchivoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Archivo"
  objects: {
    project: Prisma.$ProyectoPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    projectId: string
    kind: $Enums.ArchivoKind
    title: string
    path: string
    mimeType: string | null
    driveFileId: string | null
    sourceNotaId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["archivo"]>
  composites: {}
}

export type ArchivoGetPayload<S extends boolean | null | undefined | ArchivoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ArchivoPayload, S>

export type ArchivoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ArchivoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ArchivoCountAggregateInputType | true
  }

export interface ArchivoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Archivo'], meta: { name: 'Archivo' } }
  /**
   * Find zero or one Archivo that matches the filter.
   * @param {ArchivoFindUniqueArgs} args - Arguments to find a Archivo
   * @example
   * // Get one Archivo
   * const archivo = await prisma.archivo.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ArchivoFindUniqueArgs>(args: Prisma.SelectSubset<T, ArchivoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ArchivoClient<runtime.Types.Result.GetResult<Prisma.$ArchivoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Archivo that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ArchivoFindUniqueOrThrowArgs} args - Arguments to find a Archivo
   * @example
   * // Get one Archivo
   * const archivo = await prisma.archivo.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ArchivoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ArchivoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ArchivoClient<runtime.Types.Result.GetResult<Prisma.$ArchivoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Archivo that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArchivoFindFirstArgs} args - Arguments to find a Archivo
   * @example
   * // Get one Archivo
   * const archivo = await prisma.archivo.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ArchivoFindFirstArgs>(args?: Prisma.SelectSubset<T, ArchivoFindFirstArgs<ExtArgs>>): Prisma.Prisma__ArchivoClient<runtime.Types.Result.GetResult<Prisma.$ArchivoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Archivo that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArchivoFindFirstOrThrowArgs} args - Arguments to find a Archivo
   * @example
   * // Get one Archivo
   * const archivo = await prisma.archivo.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ArchivoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ArchivoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ArchivoClient<runtime.Types.Result.GetResult<Prisma.$ArchivoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Archivos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArchivoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Archivos
   * const archivos = await prisma.archivo.findMany()
   * 
   * // Get first 10 Archivos
   * const archivos = await prisma.archivo.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const archivoWithIdOnly = await prisma.archivo.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ArchivoFindManyArgs>(args?: Prisma.SelectSubset<T, ArchivoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ArchivoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Archivo.
   * @param {ArchivoCreateArgs} args - Arguments to create a Archivo.
   * @example
   * // Create one Archivo
   * const Archivo = await prisma.archivo.create({
   *   data: {
   *     // ... data to create a Archivo
   *   }
   * })
   * 
   */
  create<T extends ArchivoCreateArgs>(args: Prisma.SelectSubset<T, ArchivoCreateArgs<ExtArgs>>): Prisma.Prisma__ArchivoClient<runtime.Types.Result.GetResult<Prisma.$ArchivoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Archivos.
   * @param {ArchivoCreateManyArgs} args - Arguments to create many Archivos.
   * @example
   * // Create many Archivos
   * const archivo = await prisma.archivo.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ArchivoCreateManyArgs>(args?: Prisma.SelectSubset<T, ArchivoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Archivos and returns the data saved in the database.
   * @param {ArchivoCreateManyAndReturnArgs} args - Arguments to create many Archivos.
   * @example
   * // Create many Archivos
   * const archivo = await prisma.archivo.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Archivos and only return the `id`
   * const archivoWithIdOnly = await prisma.archivo.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ArchivoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ArchivoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ArchivoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Archivo.
   * @param {ArchivoDeleteArgs} args - Arguments to delete one Archivo.
   * @example
   * // Delete one Archivo
   * const Archivo = await prisma.archivo.delete({
   *   where: {
   *     // ... filter to delete one Archivo
   *   }
   * })
   * 
   */
  delete<T extends ArchivoDeleteArgs>(args: Prisma.SelectSubset<T, ArchivoDeleteArgs<ExtArgs>>): Prisma.Prisma__ArchivoClient<runtime.Types.Result.GetResult<Prisma.$ArchivoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Archivo.
   * @param {ArchivoUpdateArgs} args - Arguments to update one Archivo.
   * @example
   * // Update one Archivo
   * const archivo = await prisma.archivo.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ArchivoUpdateArgs>(args: Prisma.SelectSubset<T, ArchivoUpdateArgs<ExtArgs>>): Prisma.Prisma__ArchivoClient<runtime.Types.Result.GetResult<Prisma.$ArchivoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Archivos.
   * @param {ArchivoDeleteManyArgs} args - Arguments to filter Archivos to delete.
   * @example
   * // Delete a few Archivos
   * const { count } = await prisma.archivo.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ArchivoDeleteManyArgs>(args?: Prisma.SelectSubset<T, ArchivoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Archivos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArchivoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Archivos
   * const archivo = await prisma.archivo.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ArchivoUpdateManyArgs>(args: Prisma.SelectSubset<T, ArchivoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Archivos and returns the data updated in the database.
   * @param {ArchivoUpdateManyAndReturnArgs} args - Arguments to update many Archivos.
   * @example
   * // Update many Archivos
   * const archivo = await prisma.archivo.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Archivos and only return the `id`
   * const archivoWithIdOnly = await prisma.archivo.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ArchivoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ArchivoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ArchivoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Archivo.
   * @param {ArchivoUpsertArgs} args - Arguments to update or create a Archivo.
   * @example
   * // Update or create a Archivo
   * const archivo = await prisma.archivo.upsert({
   *   create: {
   *     // ... data to create a Archivo
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Archivo we want to update
   *   }
   * })
   */
  upsert<T extends ArchivoUpsertArgs>(args: Prisma.SelectSubset<T, ArchivoUpsertArgs<ExtArgs>>): Prisma.Prisma__ArchivoClient<runtime.Types.Result.GetResult<Prisma.$ArchivoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Archivos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArchivoCountArgs} args - Arguments to filter Archivos to count.
   * @example
   * // Count the number of Archivos
   * const count = await prisma.archivo.count({
   *   where: {
   *     // ... the filter for the Archivos we want to count
   *   }
   * })
  **/
  count<T extends ArchivoCountArgs>(
    args?: Prisma.Subset<T, ArchivoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ArchivoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Archivo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArchivoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ArchivoAggregateArgs>(args: Prisma.Subset<T, ArchivoAggregateArgs>): Prisma.PrismaPromise<GetArchivoAggregateType<T>>

  /**
   * Group by Archivo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ArchivoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ArchivoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ArchivoGroupByArgs['orderBy'] }
      : { orderBy?: ArchivoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ArchivoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetArchivoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Archivo model
 */
readonly fields: ArchivoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Archivo.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ArchivoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.ProyectoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProyectoDefaultArgs<ExtArgs>>): Prisma.Prisma__ProyectoClient<runtime.Types.Result.GetResult<Prisma.$ProyectoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Archivo model
 */
export interface ArchivoFieldRefs {
  readonly id: Prisma.FieldRef<"Archivo", 'String'>
  readonly projectId: Prisma.FieldRef<"Archivo", 'String'>
  readonly kind: Prisma.FieldRef<"Archivo", 'ArchivoKind'>
  readonly title: Prisma.FieldRef<"Archivo", 'String'>
  readonly path: Prisma.FieldRef<"Archivo", 'String'>
  readonly mimeType: Prisma.FieldRef<"Archivo", 'String'>
  readonly driveFileId: Prisma.FieldRef<"Archivo", 'String'>
  readonly sourceNotaId: Prisma.FieldRef<"Archivo", 'String'>
  readonly createdAt: Prisma.FieldRef<"Archivo", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Archivo", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Archivo findUnique
 */
export type ArchivoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Archivo
   */
  select?: Prisma.ArchivoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Archivo
   */
  omit?: Prisma.ArchivoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivoInclude<ExtArgs> | null
  /**
   * Filter, which Archivo to fetch.
   */
  where: Prisma.ArchivoWhereUniqueInput
}

/**
 * Archivo findUniqueOrThrow
 */
export type ArchivoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Archivo
   */
  select?: Prisma.ArchivoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Archivo
   */
  omit?: Prisma.ArchivoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivoInclude<ExtArgs> | null
  /**
   * Filter, which Archivo to fetch.
   */
  where: Prisma.ArchivoWhereUniqueInput
}

/**
 * Archivo findFirst
 */
export type ArchivoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Archivo
   */
  select?: Prisma.ArchivoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Archivo
   */
  omit?: Prisma.ArchivoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivoInclude<ExtArgs> | null
  /**
   * Filter, which Archivo to fetch.
   */
  where?: Prisma.ArchivoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Archivos to fetch.
   */
  orderBy?: Prisma.ArchivoOrderByWithRelationInput | Prisma.ArchivoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Archivos.
   */
  cursor?: Prisma.ArchivoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Archivos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Archivos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Archivos.
   */
  distinct?: Prisma.ArchivoScalarFieldEnum | Prisma.ArchivoScalarFieldEnum[]
}

/**
 * Archivo findFirstOrThrow
 */
export type ArchivoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Archivo
   */
  select?: Prisma.ArchivoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Archivo
   */
  omit?: Prisma.ArchivoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivoInclude<ExtArgs> | null
  /**
   * Filter, which Archivo to fetch.
   */
  where?: Prisma.ArchivoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Archivos to fetch.
   */
  orderBy?: Prisma.ArchivoOrderByWithRelationInput | Prisma.ArchivoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Archivos.
   */
  cursor?: Prisma.ArchivoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Archivos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Archivos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Archivos.
   */
  distinct?: Prisma.ArchivoScalarFieldEnum | Prisma.ArchivoScalarFieldEnum[]
}

/**
 * Archivo findMany
 */
export type ArchivoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Archivo
   */
  select?: Prisma.ArchivoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Archivo
   */
  omit?: Prisma.ArchivoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivoInclude<ExtArgs> | null
  /**
   * Filter, which Archivos to fetch.
   */
  where?: Prisma.ArchivoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Archivos to fetch.
   */
  orderBy?: Prisma.ArchivoOrderByWithRelationInput | Prisma.ArchivoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Archivos.
   */
  cursor?: Prisma.ArchivoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Archivos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Archivos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Archivos.
   */
  distinct?: Prisma.ArchivoScalarFieldEnum | Prisma.ArchivoScalarFieldEnum[]
}

/**
 * Archivo create
 */
export type ArchivoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Archivo
   */
  select?: Prisma.ArchivoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Archivo
   */
  omit?: Prisma.ArchivoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivoInclude<ExtArgs> | null
  /**
   * The data needed to create a Archivo.
   */
  data: Prisma.XOR<Prisma.ArchivoCreateInput, Prisma.ArchivoUncheckedCreateInput>
}

/**
 * Archivo createMany
 */
export type ArchivoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Archivos.
   */
  data: Prisma.ArchivoCreateManyInput | Prisma.ArchivoCreateManyInput[]
}

/**
 * Archivo createManyAndReturn
 */
export type ArchivoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Archivo
   */
  select?: Prisma.ArchivoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Archivo
   */
  omit?: Prisma.ArchivoOmit<ExtArgs> | null
  /**
   * The data used to create many Archivos.
   */
  data: Prisma.ArchivoCreateManyInput | Prisma.ArchivoCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Archivo update
 */
export type ArchivoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Archivo
   */
  select?: Prisma.ArchivoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Archivo
   */
  omit?: Prisma.ArchivoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivoInclude<ExtArgs> | null
  /**
   * The data needed to update a Archivo.
   */
  data: Prisma.XOR<Prisma.ArchivoUpdateInput, Prisma.ArchivoUncheckedUpdateInput>
  /**
   * Choose, which Archivo to update.
   */
  where: Prisma.ArchivoWhereUniqueInput
}

/**
 * Archivo updateMany
 */
export type ArchivoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Archivos.
   */
  data: Prisma.XOR<Prisma.ArchivoUpdateManyMutationInput, Prisma.ArchivoUncheckedUpdateManyInput>
  /**
   * Filter which Archivos to update
   */
  where?: Prisma.ArchivoWhereInput
  /**
   * Limit how many Archivos to update.
   */
  limit?: number
}

/**
 * Archivo updateManyAndReturn
 */
export type ArchivoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Archivo
   */
  select?: Prisma.ArchivoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Archivo
   */
  omit?: Prisma.ArchivoOmit<ExtArgs> | null
  /**
   * The data used to update Archivos.
   */
  data: Prisma.XOR<Prisma.ArchivoUpdateManyMutationInput, Prisma.ArchivoUncheckedUpdateManyInput>
  /**
   * Filter which Archivos to update
   */
  where?: Prisma.ArchivoWhereInput
  /**
   * Limit how many Archivos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Archivo upsert
 */
export type ArchivoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Archivo
   */
  select?: Prisma.ArchivoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Archivo
   */
  omit?: Prisma.ArchivoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivoInclude<ExtArgs> | null
  /**
   * The filter to search for the Archivo to update in case it exists.
   */
  where: Prisma.ArchivoWhereUniqueInput
  /**
   * In case the Archivo found by the `where` argument doesn't exist, create a new Archivo with this data.
   */
  create: Prisma.XOR<Prisma.ArchivoCreateInput, Prisma.ArchivoUncheckedCreateInput>
  /**
   * In case the Archivo was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ArchivoUpdateInput, Prisma.ArchivoUncheckedUpdateInput>
}

/**
 * Archivo delete
 */
export type ArchivoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Archivo
   */
  select?: Prisma.ArchivoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Archivo
   */
  omit?: Prisma.ArchivoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivoInclude<ExtArgs> | null
  /**
   * Filter which Archivo to delete.
   */
  where: Prisma.ArchivoWhereUniqueInput
}

/**
 * Archivo deleteMany
 */
export type ArchivoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Archivos to delete
   */
  where?: Prisma.ArchivoWhereInput
  /**
   * Limit how many Archivos to delete.
   */
  limit?: number
}

/**
 * Archivo without action
 */
export type ArchivoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Archivo
   */
  select?: Prisma.ArchivoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Archivo
   */
  omit?: Prisma.ArchivoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivoInclude<ExtArgs> | null
}
