
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DocumentTemplate` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model DocumentTemplate
 * 
 */
export type DocumentTemplateModel = runtime.Types.Result.DefaultSelection<Prisma.$DocumentTemplatePayload>

export type AggregateDocumentTemplate = {
  _count: DocumentTemplateCountAggregateOutputType | null
  _min: DocumentTemplateMinAggregateOutputType | null
  _max: DocumentTemplateMaxAggregateOutputType | null
}

export type DocumentTemplateMinAggregateOutputType = {
  id: string | null
  name: string | null
  docType: string | null
  path: string | null
  variables: string | null
  createdAt: Date | null
  updatedAt: Date | null
  projectId: string | null
}

export type DocumentTemplateMaxAggregateOutputType = {
  id: string | null
  name: string | null
  docType: string | null
  path: string | null
  variables: string | null
  createdAt: Date | null
  updatedAt: Date | null
  projectId: string | null
}

export type DocumentTemplateCountAggregateOutputType = {
  id: number
  name: number
  docType: number
  path: number
  variables: number
  createdAt: number
  updatedAt: number
  projectId: number
  _all: number
}


export type DocumentTemplateMinAggregateInputType = {
  id?: true
  name?: true
  docType?: true
  path?: true
  variables?: true
  createdAt?: true
  updatedAt?: true
  projectId?: true
}

export type DocumentTemplateMaxAggregateInputType = {
  id?: true
  name?: true
  docType?: true
  path?: true
  variables?: true
  createdAt?: true
  updatedAt?: true
  projectId?: true
}

export type DocumentTemplateCountAggregateInputType = {
  id?: true
  name?: true
  docType?: true
  path?: true
  variables?: true
  createdAt?: true
  updatedAt?: true
  projectId?: true
  _all?: true
}

export type DocumentTemplateAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DocumentTemplate to aggregate.
   */
  where?: Prisma.DocumentTemplateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DocumentTemplates to fetch.
   */
  orderBy?: Prisma.DocumentTemplateOrderByWithRelationInput | Prisma.DocumentTemplateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DocumentTemplateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DocumentTemplates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DocumentTemplates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DocumentTemplates
  **/
  _count?: true | DocumentTemplateCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DocumentTemplateMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DocumentTemplateMaxAggregateInputType
}

export type GetDocumentTemplateAggregateType<T extends DocumentTemplateAggregateArgs> = {
      [P in keyof T & keyof AggregateDocumentTemplate]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDocumentTemplate[P]>
    : Prisma.GetScalarType<T[P], AggregateDocumentTemplate[P]>
}




export type DocumentTemplateGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DocumentTemplateWhereInput
  orderBy?: Prisma.DocumentTemplateOrderByWithAggregationInput | Prisma.DocumentTemplateOrderByWithAggregationInput[]
  by: Prisma.DocumentTemplateScalarFieldEnum[] | Prisma.DocumentTemplateScalarFieldEnum
  having?: Prisma.DocumentTemplateScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DocumentTemplateCountAggregateInputType | true
  _min?: DocumentTemplateMinAggregateInputType
  _max?: DocumentTemplateMaxAggregateInputType
}

export type DocumentTemplateGroupByOutputType = {
  id: string
  name: string
  docType: string
  path: string
  variables: string | null
  createdAt: Date
  updatedAt: Date
  projectId: string | null
  _count: DocumentTemplateCountAggregateOutputType | null
  _min: DocumentTemplateMinAggregateOutputType | null
  _max: DocumentTemplateMaxAggregateOutputType | null
}

export type GetDocumentTemplateGroupByPayload<T extends DocumentTemplateGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DocumentTemplateGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DocumentTemplateGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DocumentTemplateGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DocumentTemplateGroupByOutputType[P]>
      }
    >
  >



export type DocumentTemplateWhereInput = {
  AND?: Prisma.DocumentTemplateWhereInput | Prisma.DocumentTemplateWhereInput[]
  OR?: Prisma.DocumentTemplateWhereInput[]
  NOT?: Prisma.DocumentTemplateWhereInput | Prisma.DocumentTemplateWhereInput[]
  id?: Prisma.StringFilter<"DocumentTemplate"> | string
  name?: Prisma.StringFilter<"DocumentTemplate"> | string
  docType?: Prisma.StringFilter<"DocumentTemplate"> | string
  path?: Prisma.StringFilter<"DocumentTemplate"> | string
  variables?: Prisma.StringNullableFilter<"DocumentTemplate"> | string | null
  createdAt?: Prisma.DateTimeFilter<"DocumentTemplate"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DocumentTemplate"> | Date | string
  projectId?: Prisma.StringNullableFilter<"DocumentTemplate"> | string | null
  project?: Prisma.XOR<Prisma.ProyectoNullableScalarRelationFilter, Prisma.ProyectoWhereInput> | null
}

export type DocumentTemplateOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  docType?: Prisma.SortOrder
  path?: Prisma.SortOrder
  variables?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrderInput | Prisma.SortOrder
  project?: Prisma.ProyectoOrderByWithRelationInput
}

export type DocumentTemplateWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DocumentTemplateWhereInput | Prisma.DocumentTemplateWhereInput[]
  OR?: Prisma.DocumentTemplateWhereInput[]
  NOT?: Prisma.DocumentTemplateWhereInput | Prisma.DocumentTemplateWhereInput[]
  name?: Prisma.StringFilter<"DocumentTemplate"> | string
  docType?: Prisma.StringFilter<"DocumentTemplate"> | string
  path?: Prisma.StringFilter<"DocumentTemplate"> | string
  variables?: Prisma.StringNullableFilter<"DocumentTemplate"> | string | null
  createdAt?: Prisma.DateTimeFilter<"DocumentTemplate"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DocumentTemplate"> | Date | string
  projectId?: Prisma.StringNullableFilter<"DocumentTemplate"> | string | null
  project?: Prisma.XOR<Prisma.ProyectoNullableScalarRelationFilter, Prisma.ProyectoWhereInput> | null
}, "id">

export type DocumentTemplateOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  docType?: Prisma.SortOrder
  path?: Prisma.SortOrder
  variables?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.DocumentTemplateCountOrderByAggregateInput
  _max?: Prisma.DocumentTemplateMaxOrderByAggregateInput
  _min?: Prisma.DocumentTemplateMinOrderByAggregateInput
}

export type DocumentTemplateScalarWhereWithAggregatesInput = {
  AND?: Prisma.DocumentTemplateScalarWhereWithAggregatesInput | Prisma.DocumentTemplateScalarWhereWithAggregatesInput[]
  OR?: Prisma.DocumentTemplateScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DocumentTemplateScalarWhereWithAggregatesInput | Prisma.DocumentTemplateScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DocumentTemplate"> | string
  name?: Prisma.StringWithAggregatesFilter<"DocumentTemplate"> | string
  docType?: Prisma.StringWithAggregatesFilter<"DocumentTemplate"> | string
  path?: Prisma.StringWithAggregatesFilter<"DocumentTemplate"> | string
  variables?: Prisma.StringNullableWithAggregatesFilter<"DocumentTemplate"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DocumentTemplate"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"DocumentTemplate"> | Date | string
  projectId?: Prisma.StringNullableWithAggregatesFilter<"DocumentTemplate"> | string | null
}

export type DocumentTemplateCreateInput = {
  id?: string
  name: string
  docType: string
  path: string
  variables?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  project?: Prisma.ProyectoCreateNestedOneWithoutTemplatesInput
}

export type DocumentTemplateUncheckedCreateInput = {
  id?: string
  name: string
  docType: string
  path: string
  variables?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  projectId?: string | null
}

export type DocumentTemplateUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  docType?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  variables?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProyectoUpdateOneWithoutTemplatesNestedInput
}

export type DocumentTemplateUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  docType?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  variables?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DocumentTemplateCreateManyInput = {
  id?: string
  name: string
  docType: string
  path: string
  variables?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  projectId?: string | null
}

export type DocumentTemplateUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  docType?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  variables?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DocumentTemplateUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  docType?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  variables?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projectId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type DocumentTemplateListRelationFilter = {
  every?: Prisma.DocumentTemplateWhereInput
  some?: Prisma.DocumentTemplateWhereInput
  none?: Prisma.DocumentTemplateWhereInput
}

export type DocumentTemplateOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DocumentTemplateCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  docType?: Prisma.SortOrder
  path?: Prisma.SortOrder
  variables?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
}

export type DocumentTemplateMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  docType?: Prisma.SortOrder
  path?: Prisma.SortOrder
  variables?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
}

export type DocumentTemplateMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  docType?: Prisma.SortOrder
  path?: Prisma.SortOrder
  variables?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
}

export type DocumentTemplateCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.DocumentTemplateCreateWithoutProjectInput, Prisma.DocumentTemplateUncheckedCreateWithoutProjectInput> | Prisma.DocumentTemplateCreateWithoutProjectInput[] | Prisma.DocumentTemplateUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.DocumentTemplateCreateOrConnectWithoutProjectInput | Prisma.DocumentTemplateCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.DocumentTemplateCreateManyProjectInputEnvelope
  connect?: Prisma.DocumentTemplateWhereUniqueInput | Prisma.DocumentTemplateWhereUniqueInput[]
}

export type DocumentTemplateUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.DocumentTemplateCreateWithoutProjectInput, Prisma.DocumentTemplateUncheckedCreateWithoutProjectInput> | Prisma.DocumentTemplateCreateWithoutProjectInput[] | Prisma.DocumentTemplateUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.DocumentTemplateCreateOrConnectWithoutProjectInput | Prisma.DocumentTemplateCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.DocumentTemplateCreateManyProjectInputEnvelope
  connect?: Prisma.DocumentTemplateWhereUniqueInput | Prisma.DocumentTemplateWhereUniqueInput[]
}

export type DocumentTemplateUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.DocumentTemplateCreateWithoutProjectInput, Prisma.DocumentTemplateUncheckedCreateWithoutProjectInput> | Prisma.DocumentTemplateCreateWithoutProjectInput[] | Prisma.DocumentTemplateUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.DocumentTemplateCreateOrConnectWithoutProjectInput | Prisma.DocumentTemplateCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.DocumentTemplateUpsertWithWhereUniqueWithoutProjectInput | Prisma.DocumentTemplateUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.DocumentTemplateCreateManyProjectInputEnvelope
  set?: Prisma.DocumentTemplateWhereUniqueInput | Prisma.DocumentTemplateWhereUniqueInput[]
  disconnect?: Prisma.DocumentTemplateWhereUniqueInput | Prisma.DocumentTemplateWhereUniqueInput[]
  delete?: Prisma.DocumentTemplateWhereUniqueInput | Prisma.DocumentTemplateWhereUniqueInput[]
  connect?: Prisma.DocumentTemplateWhereUniqueInput | Prisma.DocumentTemplateWhereUniqueInput[]
  update?: Prisma.DocumentTemplateUpdateWithWhereUniqueWithoutProjectInput | Prisma.DocumentTemplateUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.DocumentTemplateUpdateManyWithWhereWithoutProjectInput | Prisma.DocumentTemplateUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.DocumentTemplateScalarWhereInput | Prisma.DocumentTemplateScalarWhereInput[]
}

export type DocumentTemplateUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.DocumentTemplateCreateWithoutProjectInput, Prisma.DocumentTemplateUncheckedCreateWithoutProjectInput> | Prisma.DocumentTemplateCreateWithoutProjectInput[] | Prisma.DocumentTemplateUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.DocumentTemplateCreateOrConnectWithoutProjectInput | Prisma.DocumentTemplateCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.DocumentTemplateUpsertWithWhereUniqueWithoutProjectInput | Prisma.DocumentTemplateUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.DocumentTemplateCreateManyProjectInputEnvelope
  set?: Prisma.DocumentTemplateWhereUniqueInput | Prisma.DocumentTemplateWhereUniqueInput[]
  disconnect?: Prisma.DocumentTemplateWhereUniqueInput | Prisma.DocumentTemplateWhereUniqueInput[]
  delete?: Prisma.DocumentTemplateWhereUniqueInput | Prisma.DocumentTemplateWhereUniqueInput[]
  connect?: Prisma.DocumentTemplateWhereUniqueInput | Prisma.DocumentTemplateWhereUniqueInput[]
  update?: Prisma.DocumentTemplateUpdateWithWhereUniqueWithoutProjectInput | Prisma.DocumentTemplateUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.DocumentTemplateUpdateManyWithWhereWithoutProjectInput | Prisma.DocumentTemplateUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.DocumentTemplateScalarWhereInput | Prisma.DocumentTemplateScalarWhereInput[]
}

export type DocumentTemplateCreateWithoutProjectInput = {
  id?: string
  name: string
  docType: string
  path: string
  variables?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DocumentTemplateUncheckedCreateWithoutProjectInput = {
  id?: string
  name: string
  docType: string
  path: string
  variables?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DocumentTemplateCreateOrConnectWithoutProjectInput = {
  where: Prisma.DocumentTemplateWhereUniqueInput
  create: Prisma.XOR<Prisma.DocumentTemplateCreateWithoutProjectInput, Prisma.DocumentTemplateUncheckedCreateWithoutProjectInput>
}

export type DocumentTemplateCreateManyProjectInputEnvelope = {
  data: Prisma.DocumentTemplateCreateManyProjectInput | Prisma.DocumentTemplateCreateManyProjectInput[]
}

export type DocumentTemplateUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.DocumentTemplateWhereUniqueInput
  update: Prisma.XOR<Prisma.DocumentTemplateUpdateWithoutProjectInput, Prisma.DocumentTemplateUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.DocumentTemplateCreateWithoutProjectInput, Prisma.DocumentTemplateUncheckedCreateWithoutProjectInput>
}

export type DocumentTemplateUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.DocumentTemplateWhereUniqueInput
  data: Prisma.XOR<Prisma.DocumentTemplateUpdateWithoutProjectInput, Prisma.DocumentTemplateUncheckedUpdateWithoutProjectInput>
}

export type DocumentTemplateUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.DocumentTemplateScalarWhereInput
  data: Prisma.XOR<Prisma.DocumentTemplateUpdateManyMutationInput, Prisma.DocumentTemplateUncheckedUpdateManyWithoutProjectInput>
}

export type DocumentTemplateScalarWhereInput = {
  AND?: Prisma.DocumentTemplateScalarWhereInput | Prisma.DocumentTemplateScalarWhereInput[]
  OR?: Prisma.DocumentTemplateScalarWhereInput[]
  NOT?: Prisma.DocumentTemplateScalarWhereInput | Prisma.DocumentTemplateScalarWhereInput[]
  id?: Prisma.StringFilter<"DocumentTemplate"> | string
  name?: Prisma.StringFilter<"DocumentTemplate"> | string
  docType?: Prisma.StringFilter<"DocumentTemplate"> | string
  path?: Prisma.StringFilter<"DocumentTemplate"> | string
  variables?: Prisma.StringNullableFilter<"DocumentTemplate"> | string | null
  createdAt?: Prisma.DateTimeFilter<"DocumentTemplate"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DocumentTemplate"> | Date | string
  projectId?: Prisma.StringNullableFilter<"DocumentTemplate"> | string | null
}

export type DocumentTemplateCreateManyProjectInput = {
  id?: string
  name: string
  docType: string
  path: string
  variables?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type DocumentTemplateUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  docType?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  variables?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DocumentTemplateUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  docType?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  variables?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DocumentTemplateUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  docType?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  variables?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type DocumentTemplateSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  docType?: boolean
  path?: boolean
  variables?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  projectId?: boolean
  project?: boolean | Prisma.DocumentTemplate$projectArgs<ExtArgs>
}, ExtArgs["result"]["documentTemplate"]>

export type DocumentTemplateSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  docType?: boolean
  path?: boolean
  variables?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  projectId?: boolean
  project?: boolean | Prisma.DocumentTemplate$projectArgs<ExtArgs>
}, ExtArgs["result"]["documentTemplate"]>

export type DocumentTemplateSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  docType?: boolean
  path?: boolean
  variables?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  projectId?: boolean
  project?: boolean | Prisma.DocumentTemplate$projectArgs<ExtArgs>
}, ExtArgs["result"]["documentTemplate"]>

export type DocumentTemplateSelectScalar = {
  id?: boolean
  name?: boolean
  docType?: boolean
  path?: boolean
  variables?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  projectId?: boolean
}

export type DocumentTemplateOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "docType" | "path" | "variables" | "createdAt" | "updatedAt" | "projectId", ExtArgs["result"]["documentTemplate"]>
export type DocumentTemplateInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.DocumentTemplate$projectArgs<ExtArgs>
}
export type DocumentTemplateIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.DocumentTemplate$projectArgs<ExtArgs>
}
export type DocumentTemplateIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.DocumentTemplate$projectArgs<ExtArgs>
}

export type $DocumentTemplatePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DocumentTemplate"
  objects: {
    project: Prisma.$ProyectoPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    docType: string
    path: string
    variables: string | null
    createdAt: Date
    updatedAt: Date
    projectId: string | null
  }, ExtArgs["result"]["documentTemplate"]>
  composites: {}
}

export type DocumentTemplateGetPayload<S extends boolean | null | undefined | DocumentTemplateDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DocumentTemplatePayload, S>

export type DocumentTemplateCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DocumentTemplateFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DocumentTemplateCountAggregateInputType | true
  }

export interface DocumentTemplateDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DocumentTemplate'], meta: { name: 'DocumentTemplate' } }
  /**
   * Find zero or one DocumentTemplate that matches the filter.
   * @param {DocumentTemplateFindUniqueArgs} args - Arguments to find a DocumentTemplate
   * @example
   * // Get one DocumentTemplate
   * const documentTemplate = await prisma.documentTemplate.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DocumentTemplateFindUniqueArgs>(args: Prisma.SelectSubset<T, DocumentTemplateFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DocumentTemplateClient<runtime.Types.Result.GetResult<Prisma.$DocumentTemplatePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DocumentTemplate that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DocumentTemplateFindUniqueOrThrowArgs} args - Arguments to find a DocumentTemplate
   * @example
   * // Get one DocumentTemplate
   * const documentTemplate = await prisma.documentTemplate.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DocumentTemplateFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DocumentTemplateFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DocumentTemplateClient<runtime.Types.Result.GetResult<Prisma.$DocumentTemplatePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DocumentTemplate that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentTemplateFindFirstArgs} args - Arguments to find a DocumentTemplate
   * @example
   * // Get one DocumentTemplate
   * const documentTemplate = await prisma.documentTemplate.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DocumentTemplateFindFirstArgs>(args?: Prisma.SelectSubset<T, DocumentTemplateFindFirstArgs<ExtArgs>>): Prisma.Prisma__DocumentTemplateClient<runtime.Types.Result.GetResult<Prisma.$DocumentTemplatePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DocumentTemplate that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentTemplateFindFirstOrThrowArgs} args - Arguments to find a DocumentTemplate
   * @example
   * // Get one DocumentTemplate
   * const documentTemplate = await prisma.documentTemplate.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DocumentTemplateFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DocumentTemplateFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DocumentTemplateClient<runtime.Types.Result.GetResult<Prisma.$DocumentTemplatePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DocumentTemplates that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentTemplateFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DocumentTemplates
   * const documentTemplates = await prisma.documentTemplate.findMany()
   * 
   * // Get first 10 DocumentTemplates
   * const documentTemplates = await prisma.documentTemplate.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const documentTemplateWithIdOnly = await prisma.documentTemplate.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DocumentTemplateFindManyArgs>(args?: Prisma.SelectSubset<T, DocumentTemplateFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocumentTemplatePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DocumentTemplate.
   * @param {DocumentTemplateCreateArgs} args - Arguments to create a DocumentTemplate.
   * @example
   * // Create one DocumentTemplate
   * const DocumentTemplate = await prisma.documentTemplate.create({
   *   data: {
   *     // ... data to create a DocumentTemplate
   *   }
   * })
   * 
   */
  create<T extends DocumentTemplateCreateArgs>(args: Prisma.SelectSubset<T, DocumentTemplateCreateArgs<ExtArgs>>): Prisma.Prisma__DocumentTemplateClient<runtime.Types.Result.GetResult<Prisma.$DocumentTemplatePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DocumentTemplates.
   * @param {DocumentTemplateCreateManyArgs} args - Arguments to create many DocumentTemplates.
   * @example
   * // Create many DocumentTemplates
   * const documentTemplate = await prisma.documentTemplate.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DocumentTemplateCreateManyArgs>(args?: Prisma.SelectSubset<T, DocumentTemplateCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DocumentTemplates and returns the data saved in the database.
   * @param {DocumentTemplateCreateManyAndReturnArgs} args - Arguments to create many DocumentTemplates.
   * @example
   * // Create many DocumentTemplates
   * const documentTemplate = await prisma.documentTemplate.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DocumentTemplates and only return the `id`
   * const documentTemplateWithIdOnly = await prisma.documentTemplate.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DocumentTemplateCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DocumentTemplateCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocumentTemplatePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DocumentTemplate.
   * @param {DocumentTemplateDeleteArgs} args - Arguments to delete one DocumentTemplate.
   * @example
   * // Delete one DocumentTemplate
   * const DocumentTemplate = await prisma.documentTemplate.delete({
   *   where: {
   *     // ... filter to delete one DocumentTemplate
   *   }
   * })
   * 
   */
  delete<T extends DocumentTemplateDeleteArgs>(args: Prisma.SelectSubset<T, DocumentTemplateDeleteArgs<ExtArgs>>): Prisma.Prisma__DocumentTemplateClient<runtime.Types.Result.GetResult<Prisma.$DocumentTemplatePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DocumentTemplate.
   * @param {DocumentTemplateUpdateArgs} args - Arguments to update one DocumentTemplate.
   * @example
   * // Update one DocumentTemplate
   * const documentTemplate = await prisma.documentTemplate.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DocumentTemplateUpdateArgs>(args: Prisma.SelectSubset<T, DocumentTemplateUpdateArgs<ExtArgs>>): Prisma.Prisma__DocumentTemplateClient<runtime.Types.Result.GetResult<Prisma.$DocumentTemplatePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DocumentTemplates.
   * @param {DocumentTemplateDeleteManyArgs} args - Arguments to filter DocumentTemplates to delete.
   * @example
   * // Delete a few DocumentTemplates
   * const { count } = await prisma.documentTemplate.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DocumentTemplateDeleteManyArgs>(args?: Prisma.SelectSubset<T, DocumentTemplateDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DocumentTemplates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentTemplateUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DocumentTemplates
   * const documentTemplate = await prisma.documentTemplate.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DocumentTemplateUpdateManyArgs>(args: Prisma.SelectSubset<T, DocumentTemplateUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DocumentTemplates and returns the data updated in the database.
   * @param {DocumentTemplateUpdateManyAndReturnArgs} args - Arguments to update many DocumentTemplates.
   * @example
   * // Update many DocumentTemplates
   * const documentTemplate = await prisma.documentTemplate.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DocumentTemplates and only return the `id`
   * const documentTemplateWithIdOnly = await prisma.documentTemplate.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DocumentTemplateUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DocumentTemplateUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocumentTemplatePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DocumentTemplate.
   * @param {DocumentTemplateUpsertArgs} args - Arguments to update or create a DocumentTemplate.
   * @example
   * // Update or create a DocumentTemplate
   * const documentTemplate = await prisma.documentTemplate.upsert({
   *   create: {
   *     // ... data to create a DocumentTemplate
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DocumentTemplate we want to update
   *   }
   * })
   */
  upsert<T extends DocumentTemplateUpsertArgs>(args: Prisma.SelectSubset<T, DocumentTemplateUpsertArgs<ExtArgs>>): Prisma.Prisma__DocumentTemplateClient<runtime.Types.Result.GetResult<Prisma.$DocumentTemplatePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DocumentTemplates.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentTemplateCountArgs} args - Arguments to filter DocumentTemplates to count.
   * @example
   * // Count the number of DocumentTemplates
   * const count = await prisma.documentTemplate.count({
   *   where: {
   *     // ... the filter for the DocumentTemplates we want to count
   *   }
   * })
  **/
  count<T extends DocumentTemplateCountArgs>(
    args?: Prisma.Subset<T, DocumentTemplateCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DocumentTemplateCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DocumentTemplate.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentTemplateAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DocumentTemplateAggregateArgs>(args: Prisma.Subset<T, DocumentTemplateAggregateArgs>): Prisma.PrismaPromise<GetDocumentTemplateAggregateType<T>>

  /**
   * Group by DocumentTemplate.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentTemplateGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DocumentTemplateGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DocumentTemplateGroupByArgs['orderBy'] }
      : { orderBy?: DocumentTemplateGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DocumentTemplateGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDocumentTemplateGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DocumentTemplate model
 */
readonly fields: DocumentTemplateFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DocumentTemplate.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DocumentTemplateClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.DocumentTemplate$projectArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DocumentTemplate$projectArgs<ExtArgs>>): Prisma.Prisma__ProyectoClient<runtime.Types.Result.GetResult<Prisma.$ProyectoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DocumentTemplate model
 */
export interface DocumentTemplateFieldRefs {
  readonly id: Prisma.FieldRef<"DocumentTemplate", 'String'>
  readonly name: Prisma.FieldRef<"DocumentTemplate", 'String'>
  readonly docType: Prisma.FieldRef<"DocumentTemplate", 'String'>
  readonly path: Prisma.FieldRef<"DocumentTemplate", 'String'>
  readonly variables: Prisma.FieldRef<"DocumentTemplate", 'String'>
  readonly createdAt: Prisma.FieldRef<"DocumentTemplate", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"DocumentTemplate", 'DateTime'>
  readonly projectId: Prisma.FieldRef<"DocumentTemplate", 'String'>
}
    

// Custom InputTypes
/**
 * DocumentTemplate findUnique
 */
export type DocumentTemplateFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentTemplate
   */
  select?: Prisma.DocumentTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentTemplate
   */
  omit?: Prisma.DocumentTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentTemplateInclude<ExtArgs> | null
  /**
   * Filter, which DocumentTemplate to fetch.
   */
  where: Prisma.DocumentTemplateWhereUniqueInput
}

/**
 * DocumentTemplate findUniqueOrThrow
 */
export type DocumentTemplateFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentTemplate
   */
  select?: Prisma.DocumentTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentTemplate
   */
  omit?: Prisma.DocumentTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentTemplateInclude<ExtArgs> | null
  /**
   * Filter, which DocumentTemplate to fetch.
   */
  where: Prisma.DocumentTemplateWhereUniqueInput
}

/**
 * DocumentTemplate findFirst
 */
export type DocumentTemplateFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentTemplate
   */
  select?: Prisma.DocumentTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentTemplate
   */
  omit?: Prisma.DocumentTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentTemplateInclude<ExtArgs> | null
  /**
   * Filter, which DocumentTemplate to fetch.
   */
  where?: Prisma.DocumentTemplateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DocumentTemplates to fetch.
   */
  orderBy?: Prisma.DocumentTemplateOrderByWithRelationInput | Prisma.DocumentTemplateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DocumentTemplates.
   */
  cursor?: Prisma.DocumentTemplateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DocumentTemplates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DocumentTemplates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DocumentTemplates.
   */
  distinct?: Prisma.DocumentTemplateScalarFieldEnum | Prisma.DocumentTemplateScalarFieldEnum[]
}

/**
 * DocumentTemplate findFirstOrThrow
 */
export type DocumentTemplateFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentTemplate
   */
  select?: Prisma.DocumentTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentTemplate
   */
  omit?: Prisma.DocumentTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentTemplateInclude<ExtArgs> | null
  /**
   * Filter, which DocumentTemplate to fetch.
   */
  where?: Prisma.DocumentTemplateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DocumentTemplates to fetch.
   */
  orderBy?: Prisma.DocumentTemplateOrderByWithRelationInput | Prisma.DocumentTemplateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DocumentTemplates.
   */
  cursor?: Prisma.DocumentTemplateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DocumentTemplates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DocumentTemplates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DocumentTemplates.
   */
  distinct?: Prisma.DocumentTemplateScalarFieldEnum | Prisma.DocumentTemplateScalarFieldEnum[]
}

/**
 * DocumentTemplate findMany
 */
export type DocumentTemplateFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentTemplate
   */
  select?: Prisma.DocumentTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentTemplate
   */
  omit?: Prisma.DocumentTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentTemplateInclude<ExtArgs> | null
  /**
   * Filter, which DocumentTemplates to fetch.
   */
  where?: Prisma.DocumentTemplateWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DocumentTemplates to fetch.
   */
  orderBy?: Prisma.DocumentTemplateOrderByWithRelationInput | Prisma.DocumentTemplateOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DocumentTemplates.
   */
  cursor?: Prisma.DocumentTemplateWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DocumentTemplates from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DocumentTemplates.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DocumentTemplates.
   */
  distinct?: Prisma.DocumentTemplateScalarFieldEnum | Prisma.DocumentTemplateScalarFieldEnum[]
}

/**
 * DocumentTemplate create
 */
export type DocumentTemplateCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentTemplate
   */
  select?: Prisma.DocumentTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentTemplate
   */
  omit?: Prisma.DocumentTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentTemplateInclude<ExtArgs> | null
  /**
   * The data needed to create a DocumentTemplate.
   */
  data: Prisma.XOR<Prisma.DocumentTemplateCreateInput, Prisma.DocumentTemplateUncheckedCreateInput>
}

/**
 * DocumentTemplate createMany
 */
export type DocumentTemplateCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DocumentTemplates.
   */
  data: Prisma.DocumentTemplateCreateManyInput | Prisma.DocumentTemplateCreateManyInput[]
}

/**
 * DocumentTemplate createManyAndReturn
 */
export type DocumentTemplateCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentTemplate
   */
  select?: Prisma.DocumentTemplateSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentTemplate
   */
  omit?: Prisma.DocumentTemplateOmit<ExtArgs> | null
  /**
   * The data used to create many DocumentTemplates.
   */
  data: Prisma.DocumentTemplateCreateManyInput | Prisma.DocumentTemplateCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentTemplateIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DocumentTemplate update
 */
export type DocumentTemplateUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentTemplate
   */
  select?: Prisma.DocumentTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentTemplate
   */
  omit?: Prisma.DocumentTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentTemplateInclude<ExtArgs> | null
  /**
   * The data needed to update a DocumentTemplate.
   */
  data: Prisma.XOR<Prisma.DocumentTemplateUpdateInput, Prisma.DocumentTemplateUncheckedUpdateInput>
  /**
   * Choose, which DocumentTemplate to update.
   */
  where: Prisma.DocumentTemplateWhereUniqueInput
}

/**
 * DocumentTemplate updateMany
 */
export type DocumentTemplateUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DocumentTemplates.
   */
  data: Prisma.XOR<Prisma.DocumentTemplateUpdateManyMutationInput, Prisma.DocumentTemplateUncheckedUpdateManyInput>
  /**
   * Filter which DocumentTemplates to update
   */
  where?: Prisma.DocumentTemplateWhereInput
  /**
   * Limit how many DocumentTemplates to update.
   */
  limit?: number
}

/**
 * DocumentTemplate updateManyAndReturn
 */
export type DocumentTemplateUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentTemplate
   */
  select?: Prisma.DocumentTemplateSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentTemplate
   */
  omit?: Prisma.DocumentTemplateOmit<ExtArgs> | null
  /**
   * The data used to update DocumentTemplates.
   */
  data: Prisma.XOR<Prisma.DocumentTemplateUpdateManyMutationInput, Prisma.DocumentTemplateUncheckedUpdateManyInput>
  /**
   * Filter which DocumentTemplates to update
   */
  where?: Prisma.DocumentTemplateWhereInput
  /**
   * Limit how many DocumentTemplates to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentTemplateIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DocumentTemplate upsert
 */
export type DocumentTemplateUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentTemplate
   */
  select?: Prisma.DocumentTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentTemplate
   */
  omit?: Prisma.DocumentTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentTemplateInclude<ExtArgs> | null
  /**
   * The filter to search for the DocumentTemplate to update in case it exists.
   */
  where: Prisma.DocumentTemplateWhereUniqueInput
  /**
   * In case the DocumentTemplate found by the `where` argument doesn't exist, create a new DocumentTemplate with this data.
   */
  create: Prisma.XOR<Prisma.DocumentTemplateCreateInput, Prisma.DocumentTemplateUncheckedCreateInput>
  /**
   * In case the DocumentTemplate was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DocumentTemplateUpdateInput, Prisma.DocumentTemplateUncheckedUpdateInput>
}

/**
 * DocumentTemplate delete
 */
export type DocumentTemplateDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentTemplate
   */
  select?: Prisma.DocumentTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentTemplate
   */
  omit?: Prisma.DocumentTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentTemplateInclude<ExtArgs> | null
  /**
   * Filter which DocumentTemplate to delete.
   */
  where: Prisma.DocumentTemplateWhereUniqueInput
}

/**
 * DocumentTemplate deleteMany
 */
export type DocumentTemplateDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DocumentTemplates to delete
   */
  where?: Prisma.DocumentTemplateWhereInput
  /**
   * Limit how many DocumentTemplates to delete.
   */
  limit?: number
}

/**
 * DocumentTemplate.project
 */
export type DocumentTemplate$projectArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proyecto
   */
  select?: Prisma.ProyectoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proyecto
   */
  omit?: Prisma.ProyectoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProyectoInclude<ExtArgs> | null
  where?: Prisma.ProyectoWhereInput
}

/**
 * DocumentTemplate without action
 */
export type DocumentTemplateDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentTemplate
   */
  select?: Prisma.DocumentTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentTemplate
   */
  omit?: Prisma.DocumentTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentTemplateInclude<ExtArgs> | null
}
