
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GoogleDriveToken` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model GoogleDriveToken
 * 
 */
export type GoogleDriveTokenModel = runtime.Types.Result.DefaultSelection<Prisma.$GoogleDriveTokenPayload>

export type AggregateGoogleDriveToken = {
  _count: GoogleDriveTokenCountAggregateOutputType | null
  _min: GoogleDriveTokenMinAggregateOutputType | null
  _max: GoogleDriveTokenMaxAggregateOutputType | null
}

export type GoogleDriveTokenMinAggregateOutputType = {
  id: string | null
  refreshTokenCipher: string | null
  refreshTokenIv: string | null
  refreshTokenAuthTag: string | null
  accessToken: string | null
  accessTokenExpiresAt: Date | null
  updatedAt: Date | null
}

export type GoogleDriveTokenMaxAggregateOutputType = {
  id: string | null
  refreshTokenCipher: string | null
  refreshTokenIv: string | null
  refreshTokenAuthTag: string | null
  accessToken: string | null
  accessTokenExpiresAt: Date | null
  updatedAt: Date | null
}

export type GoogleDriveTokenCountAggregateOutputType = {
  id: number
  refreshTokenCipher: number
  refreshTokenIv: number
  refreshTokenAuthTag: number
  accessToken: number
  accessTokenExpiresAt: number
  updatedAt: number
  _all: number
}


export type GoogleDriveTokenMinAggregateInputType = {
  id?: true
  refreshTokenCipher?: true
  refreshTokenIv?: true
  refreshTokenAuthTag?: true
  accessToken?: true
  accessTokenExpiresAt?: true
  updatedAt?: true
}

export type GoogleDriveTokenMaxAggregateInputType = {
  id?: true
  refreshTokenCipher?: true
  refreshTokenIv?: true
  refreshTokenAuthTag?: true
  accessToken?: true
  accessTokenExpiresAt?: true
  updatedAt?: true
}

export type GoogleDriveTokenCountAggregateInputType = {
  id?: true
  refreshTokenCipher?: true
  refreshTokenIv?: true
  refreshTokenAuthTag?: true
  accessToken?: true
  accessTokenExpiresAt?: true
  updatedAt?: true
  _all?: true
}

export type GoogleDriveTokenAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GoogleDriveToken to aggregate.
   */
  where?: Prisma.GoogleDriveTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GoogleDriveTokens to fetch.
   */
  orderBy?: Prisma.GoogleDriveTokenOrderByWithRelationInput | Prisma.GoogleDriveTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GoogleDriveTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GoogleDriveTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GoogleDriveTokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GoogleDriveTokens
  **/
  _count?: true | GoogleDriveTokenCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GoogleDriveTokenMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GoogleDriveTokenMaxAggregateInputType
}

export type GetGoogleDriveTokenAggregateType<T extends GoogleDriveTokenAggregateArgs> = {
      [P in keyof T & keyof AggregateGoogleDriveToken]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGoogleDriveToken[P]>
    : Prisma.GetScalarType<T[P], AggregateGoogleDriveToken[P]>
}




export type GoogleDriveTokenGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GoogleDriveTokenWhereInput
  orderBy?: Prisma.GoogleDriveTokenOrderByWithAggregationInput | Prisma.GoogleDriveTokenOrderByWithAggregationInput[]
  by: Prisma.GoogleDriveTokenScalarFieldEnum[] | Prisma.GoogleDriveTokenScalarFieldEnum
  having?: Prisma.GoogleDriveTokenScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GoogleDriveTokenCountAggregateInputType | true
  _min?: GoogleDriveTokenMinAggregateInputType
  _max?: GoogleDriveTokenMaxAggregateInputType
}

export type GoogleDriveTokenGroupByOutputType = {
  id: string
  refreshTokenCipher: string
  refreshTokenIv: string
  refreshTokenAuthTag: string
  accessToken: string | null
  accessTokenExpiresAt: Date | null
  updatedAt: Date
  _count: GoogleDriveTokenCountAggregateOutputType | null
  _min: GoogleDriveTokenMinAggregateOutputType | null
  _max: GoogleDriveTokenMaxAggregateOutputType | null
}

export type GetGoogleDriveTokenGroupByPayload<T extends GoogleDriveTokenGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GoogleDriveTokenGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GoogleDriveTokenGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GoogleDriveTokenGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GoogleDriveTokenGroupByOutputType[P]>
      }
    >
  >



export type GoogleDriveTokenWhereInput = {
  AND?: Prisma.GoogleDriveTokenWhereInput | Prisma.GoogleDriveTokenWhereInput[]
  OR?: Prisma.GoogleDriveTokenWhereInput[]
  NOT?: Prisma.GoogleDriveTokenWhereInput | Prisma.GoogleDriveTokenWhereInput[]
  id?: Prisma.StringFilter<"GoogleDriveToken"> | string
  refreshTokenCipher?: Prisma.StringFilter<"GoogleDriveToken"> | string
  refreshTokenIv?: Prisma.StringFilter<"GoogleDriveToken"> | string
  refreshTokenAuthTag?: Prisma.StringFilter<"GoogleDriveToken"> | string
  accessToken?: Prisma.StringNullableFilter<"GoogleDriveToken"> | string | null
  accessTokenExpiresAt?: Prisma.DateTimeNullableFilter<"GoogleDriveToken"> | Date | string | null
  updatedAt?: Prisma.DateTimeFilter<"GoogleDriveToken"> | Date | string
}

export type GoogleDriveTokenOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  refreshTokenCipher?: Prisma.SortOrder
  refreshTokenIv?: Prisma.SortOrder
  refreshTokenAuthTag?: Prisma.SortOrder
  accessToken?: Prisma.SortOrderInput | Prisma.SortOrder
  accessTokenExpiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GoogleDriveTokenWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.GoogleDriveTokenWhereInput | Prisma.GoogleDriveTokenWhereInput[]
  OR?: Prisma.GoogleDriveTokenWhereInput[]
  NOT?: Prisma.GoogleDriveTokenWhereInput | Prisma.GoogleDriveTokenWhereInput[]
  refreshTokenCipher?: Prisma.StringFilter<"GoogleDriveToken"> | string
  refreshTokenIv?: Prisma.StringFilter<"GoogleDriveToken"> | string
  refreshTokenAuthTag?: Prisma.StringFilter<"GoogleDriveToken"> | string
  accessToken?: Prisma.StringNullableFilter<"GoogleDriveToken"> | string | null
  accessTokenExpiresAt?: Prisma.DateTimeNullableFilter<"GoogleDriveToken"> | Date | string | null
  updatedAt?: Prisma.DateTimeFilter<"GoogleDriveToken"> | Date | string
}, "id">

export type GoogleDriveTokenOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  refreshTokenCipher?: Prisma.SortOrder
  refreshTokenIv?: Prisma.SortOrder
  refreshTokenAuthTag?: Prisma.SortOrder
  accessToken?: Prisma.SortOrderInput | Prisma.SortOrder
  accessTokenExpiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.GoogleDriveTokenCountOrderByAggregateInput
  _max?: Prisma.GoogleDriveTokenMaxOrderByAggregateInput
  _min?: Prisma.GoogleDriveTokenMinOrderByAggregateInput
}

export type GoogleDriveTokenScalarWhereWithAggregatesInput = {
  AND?: Prisma.GoogleDriveTokenScalarWhereWithAggregatesInput | Prisma.GoogleDriveTokenScalarWhereWithAggregatesInput[]
  OR?: Prisma.GoogleDriveTokenScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GoogleDriveTokenScalarWhereWithAggregatesInput | Prisma.GoogleDriveTokenScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"GoogleDriveToken"> | string
  refreshTokenCipher?: Prisma.StringWithAggregatesFilter<"GoogleDriveToken"> | string
  refreshTokenIv?: Prisma.StringWithAggregatesFilter<"GoogleDriveToken"> | string
  refreshTokenAuthTag?: Prisma.StringWithAggregatesFilter<"GoogleDriveToken"> | string
  accessToken?: Prisma.StringNullableWithAggregatesFilter<"GoogleDriveToken"> | string | null
  accessTokenExpiresAt?: Prisma.DateTimeNullableWithAggregatesFilter<"GoogleDriveToken"> | Date | string | null
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"GoogleDriveToken"> | Date | string
}

export type GoogleDriveTokenCreateInput = {
  id?: string
  refreshTokenCipher: string
  refreshTokenIv: string
  refreshTokenAuthTag: string
  accessToken?: string | null
  accessTokenExpiresAt?: Date | string | null
  updatedAt?: Date | string
}

export type GoogleDriveTokenUncheckedCreateInput = {
  id?: string
  refreshTokenCipher: string
  refreshTokenIv: string
  refreshTokenAuthTag: string
  accessToken?: string | null
  accessTokenExpiresAt?: Date | string | null
  updatedAt?: Date | string
}

export type GoogleDriveTokenUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenCipher?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenIv?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenAuthTag?: Prisma.StringFieldUpdateOperationsInput | string
  accessToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accessTokenExpiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GoogleDriveTokenUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenCipher?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenIv?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenAuthTag?: Prisma.StringFieldUpdateOperationsInput | string
  accessToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accessTokenExpiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GoogleDriveTokenCreateManyInput = {
  id?: string
  refreshTokenCipher: string
  refreshTokenIv: string
  refreshTokenAuthTag: string
  accessToken?: string | null
  accessTokenExpiresAt?: Date | string | null
  updatedAt?: Date | string
}

export type GoogleDriveTokenUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenCipher?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenIv?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenAuthTag?: Prisma.StringFieldUpdateOperationsInput | string
  accessToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accessTokenExpiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GoogleDriveTokenUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenCipher?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenIv?: Prisma.StringFieldUpdateOperationsInput | string
  refreshTokenAuthTag?: Prisma.StringFieldUpdateOperationsInput | string
  accessToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  accessTokenExpiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type GoogleDriveTokenCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  refreshTokenCipher?: Prisma.SortOrder
  refreshTokenIv?: Prisma.SortOrder
  refreshTokenAuthTag?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  accessTokenExpiresAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GoogleDriveTokenMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  refreshTokenCipher?: Prisma.SortOrder
  refreshTokenIv?: Prisma.SortOrder
  refreshTokenAuthTag?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  accessTokenExpiresAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type GoogleDriveTokenMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  refreshTokenCipher?: Prisma.SortOrder
  refreshTokenIv?: Prisma.SortOrder
  refreshTokenAuthTag?: Prisma.SortOrder
  accessToken?: Prisma.SortOrder
  accessTokenExpiresAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type GoogleDriveTokenSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  refreshTokenCipher?: boolean
  refreshTokenIv?: boolean
  refreshTokenAuthTag?: boolean
  accessToken?: boolean
  accessTokenExpiresAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["googleDriveToken"]>

export type GoogleDriveTokenSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  refreshTokenCipher?: boolean
  refreshTokenIv?: boolean
  refreshTokenAuthTag?: boolean
  accessToken?: boolean
  accessTokenExpiresAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["googleDriveToken"]>

export type GoogleDriveTokenSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  refreshTokenCipher?: boolean
  refreshTokenIv?: boolean
  refreshTokenAuthTag?: boolean
  accessToken?: boolean
  accessTokenExpiresAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["googleDriveToken"]>

export type GoogleDriveTokenSelectScalar = {
  id?: boolean
  refreshTokenCipher?: boolean
  refreshTokenIv?: boolean
  refreshTokenAuthTag?: boolean
  accessToken?: boolean
  accessTokenExpiresAt?: boolean
  updatedAt?: boolean
}

export type GoogleDriveTokenOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "refreshTokenCipher" | "refreshTokenIv" | "refreshTokenAuthTag" | "accessToken" | "accessTokenExpiresAt" | "updatedAt", ExtArgs["result"]["googleDriveToken"]>

export type $GoogleDriveTokenPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GoogleDriveToken"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    refreshTokenCipher: string
    refreshTokenIv: string
    refreshTokenAuthTag: string
    accessToken: string | null
    accessTokenExpiresAt: Date | null
    updatedAt: Date
  }, ExtArgs["result"]["googleDriveToken"]>
  composites: {}
}

export type GoogleDriveTokenGetPayload<S extends boolean | null | undefined | GoogleDriveTokenDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GoogleDriveTokenPayload, S>

export type GoogleDriveTokenCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GoogleDriveTokenFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GoogleDriveTokenCountAggregateInputType | true
  }

export interface GoogleDriveTokenDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GoogleDriveToken'], meta: { name: 'GoogleDriveToken' } }
  /**
   * Find zero or one GoogleDriveToken that matches the filter.
   * @param {GoogleDriveTokenFindUniqueArgs} args - Arguments to find a GoogleDriveToken
   * @example
   * // Get one GoogleDriveToken
   * const googleDriveToken = await prisma.googleDriveToken.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GoogleDriveTokenFindUniqueArgs>(args: Prisma.SelectSubset<T, GoogleDriveTokenFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GoogleDriveTokenClient<runtime.Types.Result.GetResult<Prisma.$GoogleDriveTokenPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GoogleDriveToken that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GoogleDriveTokenFindUniqueOrThrowArgs} args - Arguments to find a GoogleDriveToken
   * @example
   * // Get one GoogleDriveToken
   * const googleDriveToken = await prisma.googleDriveToken.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GoogleDriveTokenFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GoogleDriveTokenFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GoogleDriveTokenClient<runtime.Types.Result.GetResult<Prisma.$GoogleDriveTokenPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GoogleDriveToken that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GoogleDriveTokenFindFirstArgs} args - Arguments to find a GoogleDriveToken
   * @example
   * // Get one GoogleDriveToken
   * const googleDriveToken = await prisma.googleDriveToken.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GoogleDriveTokenFindFirstArgs>(args?: Prisma.SelectSubset<T, GoogleDriveTokenFindFirstArgs<ExtArgs>>): Prisma.Prisma__GoogleDriveTokenClient<runtime.Types.Result.GetResult<Prisma.$GoogleDriveTokenPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GoogleDriveToken that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GoogleDriveTokenFindFirstOrThrowArgs} args - Arguments to find a GoogleDriveToken
   * @example
   * // Get one GoogleDriveToken
   * const googleDriveToken = await prisma.googleDriveToken.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GoogleDriveTokenFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GoogleDriveTokenFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GoogleDriveTokenClient<runtime.Types.Result.GetResult<Prisma.$GoogleDriveTokenPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GoogleDriveTokens that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GoogleDriveTokenFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GoogleDriveTokens
   * const googleDriveTokens = await prisma.googleDriveToken.findMany()
   * 
   * // Get first 10 GoogleDriveTokens
   * const googleDriveTokens = await prisma.googleDriveToken.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const googleDriveTokenWithIdOnly = await prisma.googleDriveToken.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GoogleDriveTokenFindManyArgs>(args?: Prisma.SelectSubset<T, GoogleDriveTokenFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GoogleDriveTokenPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GoogleDriveToken.
   * @param {GoogleDriveTokenCreateArgs} args - Arguments to create a GoogleDriveToken.
   * @example
   * // Create one GoogleDriveToken
   * const GoogleDriveToken = await prisma.googleDriveToken.create({
   *   data: {
   *     // ... data to create a GoogleDriveToken
   *   }
   * })
   * 
   */
  create<T extends GoogleDriveTokenCreateArgs>(args: Prisma.SelectSubset<T, GoogleDriveTokenCreateArgs<ExtArgs>>): Prisma.Prisma__GoogleDriveTokenClient<runtime.Types.Result.GetResult<Prisma.$GoogleDriveTokenPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GoogleDriveTokens.
   * @param {GoogleDriveTokenCreateManyArgs} args - Arguments to create many GoogleDriveTokens.
   * @example
   * // Create many GoogleDriveTokens
   * const googleDriveToken = await prisma.googleDriveToken.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GoogleDriveTokenCreateManyArgs>(args?: Prisma.SelectSubset<T, GoogleDriveTokenCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many GoogleDriveTokens and returns the data saved in the database.
   * @param {GoogleDriveTokenCreateManyAndReturnArgs} args - Arguments to create many GoogleDriveTokens.
   * @example
   * // Create many GoogleDriveTokens
   * const googleDriveToken = await prisma.googleDriveToken.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many GoogleDriveTokens and only return the `id`
   * const googleDriveTokenWithIdOnly = await prisma.googleDriveToken.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GoogleDriveTokenCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GoogleDriveTokenCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GoogleDriveTokenPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a GoogleDriveToken.
   * @param {GoogleDriveTokenDeleteArgs} args - Arguments to delete one GoogleDriveToken.
   * @example
   * // Delete one GoogleDriveToken
   * const GoogleDriveToken = await prisma.googleDriveToken.delete({
   *   where: {
   *     // ... filter to delete one GoogleDriveToken
   *   }
   * })
   * 
   */
  delete<T extends GoogleDriveTokenDeleteArgs>(args: Prisma.SelectSubset<T, GoogleDriveTokenDeleteArgs<ExtArgs>>): Prisma.Prisma__GoogleDriveTokenClient<runtime.Types.Result.GetResult<Prisma.$GoogleDriveTokenPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GoogleDriveToken.
   * @param {GoogleDriveTokenUpdateArgs} args - Arguments to update one GoogleDriveToken.
   * @example
   * // Update one GoogleDriveToken
   * const googleDriveToken = await prisma.googleDriveToken.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GoogleDriveTokenUpdateArgs>(args: Prisma.SelectSubset<T, GoogleDriveTokenUpdateArgs<ExtArgs>>): Prisma.Prisma__GoogleDriveTokenClient<runtime.Types.Result.GetResult<Prisma.$GoogleDriveTokenPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GoogleDriveTokens.
   * @param {GoogleDriveTokenDeleteManyArgs} args - Arguments to filter GoogleDriveTokens to delete.
   * @example
   * // Delete a few GoogleDriveTokens
   * const { count } = await prisma.googleDriveToken.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GoogleDriveTokenDeleteManyArgs>(args?: Prisma.SelectSubset<T, GoogleDriveTokenDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GoogleDriveTokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GoogleDriveTokenUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GoogleDriveTokens
   * const googleDriveToken = await prisma.googleDriveToken.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GoogleDriveTokenUpdateManyArgs>(args: Prisma.SelectSubset<T, GoogleDriveTokenUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GoogleDriveTokens and returns the data updated in the database.
   * @param {GoogleDriveTokenUpdateManyAndReturnArgs} args - Arguments to update many GoogleDriveTokens.
   * @example
   * // Update many GoogleDriveTokens
   * const googleDriveToken = await prisma.googleDriveToken.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more GoogleDriveTokens and only return the `id`
   * const googleDriveTokenWithIdOnly = await prisma.googleDriveToken.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GoogleDriveTokenUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GoogleDriveTokenUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GoogleDriveTokenPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one GoogleDriveToken.
   * @param {GoogleDriveTokenUpsertArgs} args - Arguments to update or create a GoogleDriveToken.
   * @example
   * // Update or create a GoogleDriveToken
   * const googleDriveToken = await prisma.googleDriveToken.upsert({
   *   create: {
   *     // ... data to create a GoogleDriveToken
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GoogleDriveToken we want to update
   *   }
   * })
   */
  upsert<T extends GoogleDriveTokenUpsertArgs>(args: Prisma.SelectSubset<T, GoogleDriveTokenUpsertArgs<ExtArgs>>): Prisma.Prisma__GoogleDriveTokenClient<runtime.Types.Result.GetResult<Prisma.$GoogleDriveTokenPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GoogleDriveTokens.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GoogleDriveTokenCountArgs} args - Arguments to filter GoogleDriveTokens to count.
   * @example
   * // Count the number of GoogleDriveTokens
   * const count = await prisma.googleDriveToken.count({
   *   where: {
   *     // ... the filter for the GoogleDriveTokens we want to count
   *   }
   * })
  **/
  count<T extends GoogleDriveTokenCountArgs>(
    args?: Prisma.Subset<T, GoogleDriveTokenCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GoogleDriveTokenCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GoogleDriveToken.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GoogleDriveTokenAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GoogleDriveTokenAggregateArgs>(args: Prisma.Subset<T, GoogleDriveTokenAggregateArgs>): Prisma.PrismaPromise<GetGoogleDriveTokenAggregateType<T>>

  /**
   * Group by GoogleDriveToken.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GoogleDriveTokenGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GoogleDriveTokenGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GoogleDriveTokenGroupByArgs['orderBy'] }
      : { orderBy?: GoogleDriveTokenGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GoogleDriveTokenGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGoogleDriveTokenGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GoogleDriveToken model
 */
readonly fields: GoogleDriveTokenFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GoogleDriveToken.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GoogleDriveTokenClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GoogleDriveToken model
 */
export interface GoogleDriveTokenFieldRefs {
  readonly id: Prisma.FieldRef<"GoogleDriveToken", 'String'>
  readonly refreshTokenCipher: Prisma.FieldRef<"GoogleDriveToken", 'String'>
  readonly refreshTokenIv: Prisma.FieldRef<"GoogleDriveToken", 'String'>
  readonly refreshTokenAuthTag: Prisma.FieldRef<"GoogleDriveToken", 'String'>
  readonly accessToken: Prisma.FieldRef<"GoogleDriveToken", 'String'>
  readonly accessTokenExpiresAt: Prisma.FieldRef<"GoogleDriveToken", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"GoogleDriveToken", 'DateTime'>
}
    

// Custom InputTypes
/**
 * GoogleDriveToken findUnique
 */
export type GoogleDriveTokenFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GoogleDriveToken
   */
  select?: Prisma.GoogleDriveTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GoogleDriveToken
   */
  omit?: Prisma.GoogleDriveTokenOmit<ExtArgs> | null
  /**
   * Filter, which GoogleDriveToken to fetch.
   */
  where: Prisma.GoogleDriveTokenWhereUniqueInput
}

/**
 * GoogleDriveToken findUniqueOrThrow
 */
export type GoogleDriveTokenFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GoogleDriveToken
   */
  select?: Prisma.GoogleDriveTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GoogleDriveToken
   */
  omit?: Prisma.GoogleDriveTokenOmit<ExtArgs> | null
  /**
   * Filter, which GoogleDriveToken to fetch.
   */
  where: Prisma.GoogleDriveTokenWhereUniqueInput
}

/**
 * GoogleDriveToken findFirst
 */
export type GoogleDriveTokenFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GoogleDriveToken
   */
  select?: Prisma.GoogleDriveTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GoogleDriveToken
   */
  omit?: Prisma.GoogleDriveTokenOmit<ExtArgs> | null
  /**
   * Filter, which GoogleDriveToken to fetch.
   */
  where?: Prisma.GoogleDriveTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GoogleDriveTokens to fetch.
   */
  orderBy?: Prisma.GoogleDriveTokenOrderByWithRelationInput | Prisma.GoogleDriveTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GoogleDriveTokens.
   */
  cursor?: Prisma.GoogleDriveTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GoogleDriveTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GoogleDriveTokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GoogleDriveTokens.
   */
  distinct?: Prisma.GoogleDriveTokenScalarFieldEnum | Prisma.GoogleDriveTokenScalarFieldEnum[]
}

/**
 * GoogleDriveToken findFirstOrThrow
 */
export type GoogleDriveTokenFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GoogleDriveToken
   */
  select?: Prisma.GoogleDriveTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GoogleDriveToken
   */
  omit?: Prisma.GoogleDriveTokenOmit<ExtArgs> | null
  /**
   * Filter, which GoogleDriveToken to fetch.
   */
  where?: Prisma.GoogleDriveTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GoogleDriveTokens to fetch.
   */
  orderBy?: Prisma.GoogleDriveTokenOrderByWithRelationInput | Prisma.GoogleDriveTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GoogleDriveTokens.
   */
  cursor?: Prisma.GoogleDriveTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GoogleDriveTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GoogleDriveTokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GoogleDriveTokens.
   */
  distinct?: Prisma.GoogleDriveTokenScalarFieldEnum | Prisma.GoogleDriveTokenScalarFieldEnum[]
}

/**
 * GoogleDriveToken findMany
 */
export type GoogleDriveTokenFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GoogleDriveToken
   */
  select?: Prisma.GoogleDriveTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GoogleDriveToken
   */
  omit?: Prisma.GoogleDriveTokenOmit<ExtArgs> | null
  /**
   * Filter, which GoogleDriveTokens to fetch.
   */
  where?: Prisma.GoogleDriveTokenWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GoogleDriveTokens to fetch.
   */
  orderBy?: Prisma.GoogleDriveTokenOrderByWithRelationInput | Prisma.GoogleDriveTokenOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GoogleDriveTokens.
   */
  cursor?: Prisma.GoogleDriveTokenWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GoogleDriveTokens from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GoogleDriveTokens.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GoogleDriveTokens.
   */
  distinct?: Prisma.GoogleDriveTokenScalarFieldEnum | Prisma.GoogleDriveTokenScalarFieldEnum[]
}

/**
 * GoogleDriveToken create
 */
export type GoogleDriveTokenCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GoogleDriveToken
   */
  select?: Prisma.GoogleDriveTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GoogleDriveToken
   */
  omit?: Prisma.GoogleDriveTokenOmit<ExtArgs> | null
  /**
   * The data needed to create a GoogleDriveToken.
   */
  data: Prisma.XOR<Prisma.GoogleDriveTokenCreateInput, Prisma.GoogleDriveTokenUncheckedCreateInput>
}

/**
 * GoogleDriveToken createMany
 */
export type GoogleDriveTokenCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GoogleDriveTokens.
   */
  data: Prisma.GoogleDriveTokenCreateManyInput | Prisma.GoogleDriveTokenCreateManyInput[]
}

/**
 * GoogleDriveToken createManyAndReturn
 */
export type GoogleDriveTokenCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GoogleDriveToken
   */
  select?: Prisma.GoogleDriveTokenSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GoogleDriveToken
   */
  omit?: Prisma.GoogleDriveTokenOmit<ExtArgs> | null
  /**
   * The data used to create many GoogleDriveTokens.
   */
  data: Prisma.GoogleDriveTokenCreateManyInput | Prisma.GoogleDriveTokenCreateManyInput[]
}

/**
 * GoogleDriveToken update
 */
export type GoogleDriveTokenUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GoogleDriveToken
   */
  select?: Prisma.GoogleDriveTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GoogleDriveToken
   */
  omit?: Prisma.GoogleDriveTokenOmit<ExtArgs> | null
  /**
   * The data needed to update a GoogleDriveToken.
   */
  data: Prisma.XOR<Prisma.GoogleDriveTokenUpdateInput, Prisma.GoogleDriveTokenUncheckedUpdateInput>
  /**
   * Choose, which GoogleDriveToken to update.
   */
  where: Prisma.GoogleDriveTokenWhereUniqueInput
}

/**
 * GoogleDriveToken updateMany
 */
export type GoogleDriveTokenUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GoogleDriveTokens.
   */
  data: Prisma.XOR<Prisma.GoogleDriveTokenUpdateManyMutationInput, Prisma.GoogleDriveTokenUncheckedUpdateManyInput>
  /**
   * Filter which GoogleDriveTokens to update
   */
  where?: Prisma.GoogleDriveTokenWhereInput
  /**
   * Limit how many GoogleDriveTokens to update.
   */
  limit?: number
}

/**
 * GoogleDriveToken updateManyAndReturn
 */
export type GoogleDriveTokenUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GoogleDriveToken
   */
  select?: Prisma.GoogleDriveTokenSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GoogleDriveToken
   */
  omit?: Prisma.GoogleDriveTokenOmit<ExtArgs> | null
  /**
   * The data used to update GoogleDriveTokens.
   */
  data: Prisma.XOR<Prisma.GoogleDriveTokenUpdateManyMutationInput, Prisma.GoogleDriveTokenUncheckedUpdateManyInput>
  /**
   * Filter which GoogleDriveTokens to update
   */
  where?: Prisma.GoogleDriveTokenWhereInput
  /**
   * Limit how many GoogleDriveTokens to update.
   */
  limit?: number
}

/**
 * GoogleDriveToken upsert
 */
export type GoogleDriveTokenUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GoogleDriveToken
   */
  select?: Prisma.GoogleDriveTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GoogleDriveToken
   */
  omit?: Prisma.GoogleDriveTokenOmit<ExtArgs> | null
  /**
   * The filter to search for the GoogleDriveToken to update in case it exists.
   */
  where: Prisma.GoogleDriveTokenWhereUniqueInput
  /**
   * In case the GoogleDriveToken found by the `where` argument doesn't exist, create a new GoogleDriveToken with this data.
   */
  create: Prisma.XOR<Prisma.GoogleDriveTokenCreateInput, Prisma.GoogleDriveTokenUncheckedCreateInput>
  /**
   * In case the GoogleDriveToken was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GoogleDriveTokenUpdateInput, Prisma.GoogleDriveTokenUncheckedUpdateInput>
}

/**
 * GoogleDriveToken delete
 */
export type GoogleDriveTokenDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GoogleDriveToken
   */
  select?: Prisma.GoogleDriveTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GoogleDriveToken
   */
  omit?: Prisma.GoogleDriveTokenOmit<ExtArgs> | null
  /**
   * Filter which GoogleDriveToken to delete.
   */
  where: Prisma.GoogleDriveTokenWhereUniqueInput
}

/**
 * GoogleDriveToken deleteMany
 */
export type GoogleDriveTokenDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GoogleDriveTokens to delete
   */
  where?: Prisma.GoogleDriveTokenWhereInput
  /**
   * Limit how many GoogleDriveTokens to delete.
   */
  limit?: number
}

/**
 * GoogleDriveToken without action
 */
export type GoogleDriveTokenDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GoogleDriveToken
   */
  select?: Prisma.GoogleDriveTokenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GoogleDriveToken
   */
  omit?: Prisma.GoogleDriveTokenOmit<ExtArgs> | null
}
