
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Nota` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Nota
 * 
 */
export type NotaModel = runtime.Types.Result.DefaultSelection<Prisma.$NotaPayload>

export type AggregateNota = {
  _count: NotaCountAggregateOutputType | null
  _min: NotaMinAggregateOutputType | null
  _max: NotaMaxAggregateOutputType | null
}

export type NotaMinAggregateOutputType = {
  id: string | null
  title: string | null
  content: string | null
  createdAt: Date | null
  updatedAt: Date | null
  projectId: string | null
  taskId: string | null
}

export type NotaMaxAggregateOutputType = {
  id: string | null
  title: string | null
  content: string | null
  createdAt: Date | null
  updatedAt: Date | null
  projectId: string | null
  taskId: string | null
}

export type NotaCountAggregateOutputType = {
  id: number
  title: number
  content: number
  createdAt: number
  updatedAt: number
  projectId: number
  taskId: number
  _all: number
}


export type NotaMinAggregateInputType = {
  id?: true
  title?: true
  content?: true
  createdAt?: true
  updatedAt?: true
  projectId?: true
  taskId?: true
}

export type NotaMaxAggregateInputType = {
  id?: true
  title?: true
  content?: true
  createdAt?: true
  updatedAt?: true
  projectId?: true
  taskId?: true
}

export type NotaCountAggregateInputType = {
  id?: true
  title?: true
  content?: true
  createdAt?: true
  updatedAt?: true
  projectId?: true
  taskId?: true
  _all?: true
}

export type NotaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Nota to aggregate.
   */
  where?: Prisma.NotaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Notas to fetch.
   */
  orderBy?: Prisma.NotaOrderByWithRelationInput | Prisma.NotaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NotaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Notas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Notas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Notas
  **/
  _count?: true | NotaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NotaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NotaMaxAggregateInputType
}

export type GetNotaAggregateType<T extends NotaAggregateArgs> = {
      [P in keyof T & keyof AggregateNota]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNota[P]>
    : Prisma.GetScalarType<T[P], AggregateNota[P]>
}




export type NotaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NotaWhereInput
  orderBy?: Prisma.NotaOrderByWithAggregationInput | Prisma.NotaOrderByWithAggregationInput[]
  by: Prisma.NotaScalarFieldEnum[] | Prisma.NotaScalarFieldEnum
  having?: Prisma.NotaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NotaCountAggregateInputType | true
  _min?: NotaMinAggregateInputType
  _max?: NotaMaxAggregateInputType
}

export type NotaGroupByOutputType = {
  id: string
  title: string
  content: string
  createdAt: Date
  updatedAt: Date
  projectId: string
  taskId: string | null
  _count: NotaCountAggregateOutputType | null
  _min: NotaMinAggregateOutputType | null
  _max: NotaMaxAggregateOutputType | null
}

export type GetNotaGroupByPayload<T extends NotaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NotaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NotaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NotaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NotaGroupByOutputType[P]>
      }
    >
  >



export type NotaWhereInput = {
  AND?: Prisma.NotaWhereInput | Prisma.NotaWhereInput[]
  OR?: Prisma.NotaWhereInput[]
  NOT?: Prisma.NotaWhereInput | Prisma.NotaWhereInput[]
  id?: Prisma.StringFilter<"Nota"> | string
  title?: Prisma.StringFilter<"Nota"> | string
  content?: Prisma.StringFilter<"Nota"> | string
  createdAt?: Prisma.DateTimeFilter<"Nota"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Nota"> | Date | string
  projectId?: Prisma.StringFilter<"Nota"> | string
  taskId?: Prisma.StringNullableFilter<"Nota"> | string | null
  project?: Prisma.XOR<Prisma.ProyectoScalarRelationFilter, Prisma.ProyectoWhereInput>
  task?: Prisma.XOR<Prisma.TareaNullableScalarRelationFilter, Prisma.TareaWhereInput> | null
}

export type NotaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  taskId?: Prisma.SortOrderInput | Prisma.SortOrder
  project?: Prisma.ProyectoOrderByWithRelationInput
  task?: Prisma.TareaOrderByWithRelationInput
}

export type NotaWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.NotaWhereInput | Prisma.NotaWhereInput[]
  OR?: Prisma.NotaWhereInput[]
  NOT?: Prisma.NotaWhereInput | Prisma.NotaWhereInput[]
  title?: Prisma.StringFilter<"Nota"> | string
  content?: Prisma.StringFilter<"Nota"> | string
  createdAt?: Prisma.DateTimeFilter<"Nota"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Nota"> | Date | string
  projectId?: Prisma.StringFilter<"Nota"> | string
  taskId?: Prisma.StringNullableFilter<"Nota"> | string | null
  project?: Prisma.XOR<Prisma.ProyectoScalarRelationFilter, Prisma.ProyectoWhereInput>
  task?: Prisma.XOR<Prisma.TareaNullableScalarRelationFilter, Prisma.TareaWhereInput> | null
}, "id">

export type NotaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  taskId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.NotaCountOrderByAggregateInput
  _max?: Prisma.NotaMaxOrderByAggregateInput
  _min?: Prisma.NotaMinOrderByAggregateInput
}

export type NotaScalarWhereWithAggregatesInput = {
  AND?: Prisma.NotaScalarWhereWithAggregatesInput | Prisma.NotaScalarWhereWithAggregatesInput[]
  OR?: Prisma.NotaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NotaScalarWhereWithAggregatesInput | Prisma.NotaScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Nota"> | string
  title?: Prisma.StringWithAggregatesFilter<"Nota"> | string
  content?: Prisma.StringWithAggregatesFilter<"Nota"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Nota"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Nota"> | Date | string
  projectId?: Prisma.StringWithAggregatesFilter<"Nota"> | string
  taskId?: Prisma.StringNullableWithAggregatesFilter<"Nota"> | string | null
}

export type NotaCreateInput = {
  id?: string
  title: string
  content: string
  createdAt?: Date | string
  updatedAt?: Date | string
  project: Prisma.ProyectoCreateNestedOneWithoutNotesInput
  task?: Prisma.TareaCreateNestedOneWithoutNotesInput
}

export type NotaUncheckedCreateInput = {
  id?: string
  title: string
  content: string
  createdAt?: Date | string
  updatedAt?: Date | string
  projectId: string
  taskId?: string | null
}

export type NotaUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProyectoUpdateOneRequiredWithoutNotesNestedInput
  task?: Prisma.TareaUpdateOneWithoutNotesNestedInput
}

export type NotaUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type NotaCreateManyInput = {
  id?: string
  title: string
  content: string
  createdAt?: Date | string
  updatedAt?: Date | string
  projectId: string
  taskId?: string | null
}

export type NotaUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NotaUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type NotaListRelationFilter = {
  every?: Prisma.NotaWhereInput
  some?: Prisma.NotaWhereInput
  none?: Prisma.NotaWhereInput
}

export type NotaOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NotaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
}

export type NotaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
}

export type NotaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  content?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
}

export type NotaCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.NotaCreateWithoutProjectInput, Prisma.NotaUncheckedCreateWithoutProjectInput> | Prisma.NotaCreateWithoutProjectInput[] | Prisma.NotaUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.NotaCreateOrConnectWithoutProjectInput | Prisma.NotaCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.NotaCreateManyProjectInputEnvelope
  connect?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
}

export type NotaUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.NotaCreateWithoutProjectInput, Prisma.NotaUncheckedCreateWithoutProjectInput> | Prisma.NotaCreateWithoutProjectInput[] | Prisma.NotaUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.NotaCreateOrConnectWithoutProjectInput | Prisma.NotaCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.NotaCreateManyProjectInputEnvelope
  connect?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
}

export type NotaUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.NotaCreateWithoutProjectInput, Prisma.NotaUncheckedCreateWithoutProjectInput> | Prisma.NotaCreateWithoutProjectInput[] | Prisma.NotaUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.NotaCreateOrConnectWithoutProjectInput | Prisma.NotaCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.NotaUpsertWithWhereUniqueWithoutProjectInput | Prisma.NotaUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.NotaCreateManyProjectInputEnvelope
  set?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
  disconnect?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
  delete?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
  connect?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
  update?: Prisma.NotaUpdateWithWhereUniqueWithoutProjectInput | Prisma.NotaUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.NotaUpdateManyWithWhereWithoutProjectInput | Prisma.NotaUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.NotaScalarWhereInput | Prisma.NotaScalarWhereInput[]
}

export type NotaUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.NotaCreateWithoutProjectInput, Prisma.NotaUncheckedCreateWithoutProjectInput> | Prisma.NotaCreateWithoutProjectInput[] | Prisma.NotaUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.NotaCreateOrConnectWithoutProjectInput | Prisma.NotaCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.NotaUpsertWithWhereUniqueWithoutProjectInput | Prisma.NotaUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.NotaCreateManyProjectInputEnvelope
  set?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
  disconnect?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
  delete?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
  connect?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
  update?: Prisma.NotaUpdateWithWhereUniqueWithoutProjectInput | Prisma.NotaUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.NotaUpdateManyWithWhereWithoutProjectInput | Prisma.NotaUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.NotaScalarWhereInput | Prisma.NotaScalarWhereInput[]
}

export type NotaCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.NotaCreateWithoutTaskInput, Prisma.NotaUncheckedCreateWithoutTaskInput> | Prisma.NotaCreateWithoutTaskInput[] | Prisma.NotaUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.NotaCreateOrConnectWithoutTaskInput | Prisma.NotaCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.NotaCreateManyTaskInputEnvelope
  connect?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
}

export type NotaUncheckedCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.NotaCreateWithoutTaskInput, Prisma.NotaUncheckedCreateWithoutTaskInput> | Prisma.NotaCreateWithoutTaskInput[] | Prisma.NotaUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.NotaCreateOrConnectWithoutTaskInput | Prisma.NotaCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.NotaCreateManyTaskInputEnvelope
  connect?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
}

export type NotaUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.NotaCreateWithoutTaskInput, Prisma.NotaUncheckedCreateWithoutTaskInput> | Prisma.NotaCreateWithoutTaskInput[] | Prisma.NotaUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.NotaCreateOrConnectWithoutTaskInput | Prisma.NotaCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.NotaUpsertWithWhereUniqueWithoutTaskInput | Prisma.NotaUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.NotaCreateManyTaskInputEnvelope
  set?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
  disconnect?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
  delete?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
  connect?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
  update?: Prisma.NotaUpdateWithWhereUniqueWithoutTaskInput | Prisma.NotaUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.NotaUpdateManyWithWhereWithoutTaskInput | Prisma.NotaUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.NotaScalarWhereInput | Prisma.NotaScalarWhereInput[]
}

export type NotaUncheckedUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.NotaCreateWithoutTaskInput, Prisma.NotaUncheckedCreateWithoutTaskInput> | Prisma.NotaCreateWithoutTaskInput[] | Prisma.NotaUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.NotaCreateOrConnectWithoutTaskInput | Prisma.NotaCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.NotaUpsertWithWhereUniqueWithoutTaskInput | Prisma.NotaUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.NotaCreateManyTaskInputEnvelope
  set?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
  disconnect?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
  delete?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
  connect?: Prisma.NotaWhereUniqueInput | Prisma.NotaWhereUniqueInput[]
  update?: Prisma.NotaUpdateWithWhereUniqueWithoutTaskInput | Prisma.NotaUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.NotaUpdateManyWithWhereWithoutTaskInput | Prisma.NotaUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.NotaScalarWhereInput | Prisma.NotaScalarWhereInput[]
}

export type NotaCreateWithoutProjectInput = {
  id?: string
  title: string
  content: string
  createdAt?: Date | string
  updatedAt?: Date | string
  task?: Prisma.TareaCreateNestedOneWithoutNotesInput
}

export type NotaUncheckedCreateWithoutProjectInput = {
  id?: string
  title: string
  content: string
  createdAt?: Date | string
  updatedAt?: Date | string
  taskId?: string | null
}

export type NotaCreateOrConnectWithoutProjectInput = {
  where: Prisma.NotaWhereUniqueInput
  create: Prisma.XOR<Prisma.NotaCreateWithoutProjectInput, Prisma.NotaUncheckedCreateWithoutProjectInput>
}

export type NotaCreateManyProjectInputEnvelope = {
  data: Prisma.NotaCreateManyProjectInput | Prisma.NotaCreateManyProjectInput[]
}

export type NotaUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.NotaWhereUniqueInput
  update: Prisma.XOR<Prisma.NotaUpdateWithoutProjectInput, Prisma.NotaUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.NotaCreateWithoutProjectInput, Prisma.NotaUncheckedCreateWithoutProjectInput>
}

export type NotaUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.NotaWhereUniqueInput
  data: Prisma.XOR<Prisma.NotaUpdateWithoutProjectInput, Prisma.NotaUncheckedUpdateWithoutProjectInput>
}

export type NotaUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.NotaScalarWhereInput
  data: Prisma.XOR<Prisma.NotaUpdateManyMutationInput, Prisma.NotaUncheckedUpdateManyWithoutProjectInput>
}

export type NotaScalarWhereInput = {
  AND?: Prisma.NotaScalarWhereInput | Prisma.NotaScalarWhereInput[]
  OR?: Prisma.NotaScalarWhereInput[]
  NOT?: Prisma.NotaScalarWhereInput | Prisma.NotaScalarWhereInput[]
  id?: Prisma.StringFilter<"Nota"> | string
  title?: Prisma.StringFilter<"Nota"> | string
  content?: Prisma.StringFilter<"Nota"> | string
  createdAt?: Prisma.DateTimeFilter<"Nota"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Nota"> | Date | string
  projectId?: Prisma.StringFilter<"Nota"> | string
  taskId?: Prisma.StringNullableFilter<"Nota"> | string | null
}

export type NotaCreateWithoutTaskInput = {
  id?: string
  title: string
  content: string
  createdAt?: Date | string
  updatedAt?: Date | string
  project: Prisma.ProyectoCreateNestedOneWithoutNotesInput
}

export type NotaUncheckedCreateWithoutTaskInput = {
  id?: string
  title: string
  content: string
  createdAt?: Date | string
  updatedAt?: Date | string
  projectId: string
}

export type NotaCreateOrConnectWithoutTaskInput = {
  where: Prisma.NotaWhereUniqueInput
  create: Prisma.XOR<Prisma.NotaCreateWithoutTaskInput, Prisma.NotaUncheckedCreateWithoutTaskInput>
}

export type NotaCreateManyTaskInputEnvelope = {
  data: Prisma.NotaCreateManyTaskInput | Prisma.NotaCreateManyTaskInput[]
}

export type NotaUpsertWithWhereUniqueWithoutTaskInput = {
  where: Prisma.NotaWhereUniqueInput
  update: Prisma.XOR<Prisma.NotaUpdateWithoutTaskInput, Prisma.NotaUncheckedUpdateWithoutTaskInput>
  create: Prisma.XOR<Prisma.NotaCreateWithoutTaskInput, Prisma.NotaUncheckedCreateWithoutTaskInput>
}

export type NotaUpdateWithWhereUniqueWithoutTaskInput = {
  where: Prisma.NotaWhereUniqueInput
  data: Prisma.XOR<Prisma.NotaUpdateWithoutTaskInput, Prisma.NotaUncheckedUpdateWithoutTaskInput>
}

export type NotaUpdateManyWithWhereWithoutTaskInput = {
  where: Prisma.NotaScalarWhereInput
  data: Prisma.XOR<Prisma.NotaUpdateManyMutationInput, Prisma.NotaUncheckedUpdateManyWithoutTaskInput>
}

export type NotaCreateManyProjectInput = {
  id?: string
  title: string
  content: string
  createdAt?: Date | string
  updatedAt?: Date | string
  taskId?: string | null
}

export type NotaUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  task?: Prisma.TareaUpdateOneWithoutNotesNestedInput
}

export type NotaUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type NotaUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  taskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type NotaCreateManyTaskInput = {
  id?: string
  title: string
  content: string
  createdAt?: Date | string
  updatedAt?: Date | string
  projectId: string
}

export type NotaUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProyectoUpdateOneRequiredWithoutNotesNestedInput
}

export type NotaUncheckedUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type NotaUncheckedUpdateManyWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type NotaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  projectId?: boolean
  taskId?: boolean
  project?: boolean | Prisma.ProyectoDefaultArgs<ExtArgs>
  task?: boolean | Prisma.Nota$taskArgs<ExtArgs>
}, ExtArgs["result"]["nota"]>

export type NotaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  projectId?: boolean
  taskId?: boolean
  project?: boolean | Prisma.ProyectoDefaultArgs<ExtArgs>
  task?: boolean | Prisma.Nota$taskArgs<ExtArgs>
}, ExtArgs["result"]["nota"]>

export type NotaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  content?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  projectId?: boolean
  taskId?: boolean
  project?: boolean | Prisma.ProyectoDefaultArgs<ExtArgs>
  task?: boolean | Prisma.Nota$taskArgs<ExtArgs>
}, ExtArgs["result"]["nota"]>

export type NotaSelectScalar = {
  id?: boolean
  title?: boolean
  content?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  projectId?: boolean
  taskId?: boolean
}

export type NotaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "content" | "createdAt" | "updatedAt" | "projectId" | "taskId", ExtArgs["result"]["nota"]>
export type NotaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProyectoDefaultArgs<ExtArgs>
  task?: boolean | Prisma.Nota$taskArgs<ExtArgs>
}
export type NotaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProyectoDefaultArgs<ExtArgs>
  task?: boolean | Prisma.Nota$taskArgs<ExtArgs>
}
export type NotaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProyectoDefaultArgs<ExtArgs>
  task?: boolean | Prisma.Nota$taskArgs<ExtArgs>
}

export type $NotaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Nota"
  objects: {
    project: Prisma.$ProyectoPayload<ExtArgs>
    task: Prisma.$TareaPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    content: string
    createdAt: Date
    updatedAt: Date
    projectId: string
    taskId: string | null
  }, ExtArgs["result"]["nota"]>
  composites: {}
}

export type NotaGetPayload<S extends boolean | null | undefined | NotaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NotaPayload, S>

export type NotaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NotaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NotaCountAggregateInputType | true
  }

export interface NotaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Nota'], meta: { name: 'Nota' } }
  /**
   * Find zero or one Nota that matches the filter.
   * @param {NotaFindUniqueArgs} args - Arguments to find a Nota
   * @example
   * // Get one Nota
   * const nota = await prisma.nota.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NotaFindUniqueArgs>(args: Prisma.SelectSubset<T, NotaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NotaClient<runtime.Types.Result.GetResult<Prisma.$NotaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Nota that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NotaFindUniqueOrThrowArgs} args - Arguments to find a Nota
   * @example
   * // Get one Nota
   * const nota = await prisma.nota.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NotaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NotaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NotaClient<runtime.Types.Result.GetResult<Prisma.$NotaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Nota that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotaFindFirstArgs} args - Arguments to find a Nota
   * @example
   * // Get one Nota
   * const nota = await prisma.nota.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NotaFindFirstArgs>(args?: Prisma.SelectSubset<T, NotaFindFirstArgs<ExtArgs>>): Prisma.Prisma__NotaClient<runtime.Types.Result.GetResult<Prisma.$NotaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Nota that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotaFindFirstOrThrowArgs} args - Arguments to find a Nota
   * @example
   * // Get one Nota
   * const nota = await prisma.nota.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NotaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NotaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NotaClient<runtime.Types.Result.GetResult<Prisma.$NotaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Notas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Notas
   * const notas = await prisma.nota.findMany()
   * 
   * // Get first 10 Notas
   * const notas = await prisma.nota.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const notaWithIdOnly = await prisma.nota.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NotaFindManyArgs>(args?: Prisma.SelectSubset<T, NotaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Nota.
   * @param {NotaCreateArgs} args - Arguments to create a Nota.
   * @example
   * // Create one Nota
   * const Nota = await prisma.nota.create({
   *   data: {
   *     // ... data to create a Nota
   *   }
   * })
   * 
   */
  create<T extends NotaCreateArgs>(args: Prisma.SelectSubset<T, NotaCreateArgs<ExtArgs>>): Prisma.Prisma__NotaClient<runtime.Types.Result.GetResult<Prisma.$NotaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Notas.
   * @param {NotaCreateManyArgs} args - Arguments to create many Notas.
   * @example
   * // Create many Notas
   * const nota = await prisma.nota.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NotaCreateManyArgs>(args?: Prisma.SelectSubset<T, NotaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Notas and returns the data saved in the database.
   * @param {NotaCreateManyAndReturnArgs} args - Arguments to create many Notas.
   * @example
   * // Create many Notas
   * const nota = await prisma.nota.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Notas and only return the `id`
   * const notaWithIdOnly = await prisma.nota.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NotaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NotaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Nota.
   * @param {NotaDeleteArgs} args - Arguments to delete one Nota.
   * @example
   * // Delete one Nota
   * const Nota = await prisma.nota.delete({
   *   where: {
   *     // ... filter to delete one Nota
   *   }
   * })
   * 
   */
  delete<T extends NotaDeleteArgs>(args: Prisma.SelectSubset<T, NotaDeleteArgs<ExtArgs>>): Prisma.Prisma__NotaClient<runtime.Types.Result.GetResult<Prisma.$NotaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Nota.
   * @param {NotaUpdateArgs} args - Arguments to update one Nota.
   * @example
   * // Update one Nota
   * const nota = await prisma.nota.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NotaUpdateArgs>(args: Prisma.SelectSubset<T, NotaUpdateArgs<ExtArgs>>): Prisma.Prisma__NotaClient<runtime.Types.Result.GetResult<Prisma.$NotaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Notas.
   * @param {NotaDeleteManyArgs} args - Arguments to filter Notas to delete.
   * @example
   * // Delete a few Notas
   * const { count } = await prisma.nota.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NotaDeleteManyArgs>(args?: Prisma.SelectSubset<T, NotaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Notas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Notas
   * const nota = await prisma.nota.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NotaUpdateManyArgs>(args: Prisma.SelectSubset<T, NotaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Notas and returns the data updated in the database.
   * @param {NotaUpdateManyAndReturnArgs} args - Arguments to update many Notas.
   * @example
   * // Update many Notas
   * const nota = await prisma.nota.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Notas and only return the `id`
   * const notaWithIdOnly = await prisma.nota.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NotaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NotaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Nota.
   * @param {NotaUpsertArgs} args - Arguments to update or create a Nota.
   * @example
   * // Update or create a Nota
   * const nota = await prisma.nota.upsert({
   *   create: {
   *     // ... data to create a Nota
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Nota we want to update
   *   }
   * })
   */
  upsert<T extends NotaUpsertArgs>(args: Prisma.SelectSubset<T, NotaUpsertArgs<ExtArgs>>): Prisma.Prisma__NotaClient<runtime.Types.Result.GetResult<Prisma.$NotaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Notas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotaCountArgs} args - Arguments to filter Notas to count.
   * @example
   * // Count the number of Notas
   * const count = await prisma.nota.count({
   *   where: {
   *     // ... the filter for the Notas we want to count
   *   }
   * })
  **/
  count<T extends NotaCountArgs>(
    args?: Prisma.Subset<T, NotaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NotaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Nota.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NotaAggregateArgs>(args: Prisma.Subset<T, NotaAggregateArgs>): Prisma.PrismaPromise<GetNotaAggregateType<T>>

  /**
   * Group by Nota.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NotaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NotaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NotaGroupByArgs['orderBy'] }
      : { orderBy?: NotaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NotaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNotaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Nota model
 */
readonly fields: NotaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Nota.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NotaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.ProyectoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProyectoDefaultArgs<ExtArgs>>): Prisma.Prisma__ProyectoClient<runtime.Types.Result.GetResult<Prisma.$ProyectoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  task<T extends Prisma.Nota$taskArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Nota$taskArgs<ExtArgs>>): Prisma.Prisma__TareaClient<runtime.Types.Result.GetResult<Prisma.$TareaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Nota model
 */
export interface NotaFieldRefs {
  readonly id: Prisma.FieldRef<"Nota", 'String'>
  readonly title: Prisma.FieldRef<"Nota", 'String'>
  readonly content: Prisma.FieldRef<"Nota", 'String'>
  readonly createdAt: Prisma.FieldRef<"Nota", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Nota", 'DateTime'>
  readonly projectId: Prisma.FieldRef<"Nota", 'String'>
  readonly taskId: Prisma.FieldRef<"Nota", 'String'>
}
    

// Custom InputTypes
/**
 * Nota findUnique
 */
export type NotaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Nota
   */
  select?: Prisma.NotaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Nota
   */
  omit?: Prisma.NotaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotaInclude<ExtArgs> | null
  /**
   * Filter, which Nota to fetch.
   */
  where: Prisma.NotaWhereUniqueInput
}

/**
 * Nota findUniqueOrThrow
 */
export type NotaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Nota
   */
  select?: Prisma.NotaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Nota
   */
  omit?: Prisma.NotaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotaInclude<ExtArgs> | null
  /**
   * Filter, which Nota to fetch.
   */
  where: Prisma.NotaWhereUniqueInput
}

/**
 * Nota findFirst
 */
export type NotaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Nota
   */
  select?: Prisma.NotaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Nota
   */
  omit?: Prisma.NotaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotaInclude<ExtArgs> | null
  /**
   * Filter, which Nota to fetch.
   */
  where?: Prisma.NotaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Notas to fetch.
   */
  orderBy?: Prisma.NotaOrderByWithRelationInput | Prisma.NotaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Notas.
   */
  cursor?: Prisma.NotaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Notas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Notas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Notas.
   */
  distinct?: Prisma.NotaScalarFieldEnum | Prisma.NotaScalarFieldEnum[]
}

/**
 * Nota findFirstOrThrow
 */
export type NotaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Nota
   */
  select?: Prisma.NotaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Nota
   */
  omit?: Prisma.NotaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotaInclude<ExtArgs> | null
  /**
   * Filter, which Nota to fetch.
   */
  where?: Prisma.NotaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Notas to fetch.
   */
  orderBy?: Prisma.NotaOrderByWithRelationInput | Prisma.NotaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Notas.
   */
  cursor?: Prisma.NotaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Notas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Notas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Notas.
   */
  distinct?: Prisma.NotaScalarFieldEnum | Prisma.NotaScalarFieldEnum[]
}

/**
 * Nota findMany
 */
export type NotaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Nota
   */
  select?: Prisma.NotaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Nota
   */
  omit?: Prisma.NotaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotaInclude<ExtArgs> | null
  /**
   * Filter, which Notas to fetch.
   */
  where?: Prisma.NotaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Notas to fetch.
   */
  orderBy?: Prisma.NotaOrderByWithRelationInput | Prisma.NotaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Notas.
   */
  cursor?: Prisma.NotaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Notas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Notas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Notas.
   */
  distinct?: Prisma.NotaScalarFieldEnum | Prisma.NotaScalarFieldEnum[]
}

/**
 * Nota create
 */
export type NotaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Nota
   */
  select?: Prisma.NotaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Nota
   */
  omit?: Prisma.NotaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotaInclude<ExtArgs> | null
  /**
   * The data needed to create a Nota.
   */
  data: Prisma.XOR<Prisma.NotaCreateInput, Prisma.NotaUncheckedCreateInput>
}

/**
 * Nota createMany
 */
export type NotaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Notas.
   */
  data: Prisma.NotaCreateManyInput | Prisma.NotaCreateManyInput[]
}

/**
 * Nota createManyAndReturn
 */
export type NotaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Nota
   */
  select?: Prisma.NotaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Nota
   */
  omit?: Prisma.NotaOmit<ExtArgs> | null
  /**
   * The data used to create many Notas.
   */
  data: Prisma.NotaCreateManyInput | Prisma.NotaCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotaIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Nota update
 */
export type NotaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Nota
   */
  select?: Prisma.NotaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Nota
   */
  omit?: Prisma.NotaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotaInclude<ExtArgs> | null
  /**
   * The data needed to update a Nota.
   */
  data: Prisma.XOR<Prisma.NotaUpdateInput, Prisma.NotaUncheckedUpdateInput>
  /**
   * Choose, which Nota to update.
   */
  where: Prisma.NotaWhereUniqueInput
}

/**
 * Nota updateMany
 */
export type NotaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Notas.
   */
  data: Prisma.XOR<Prisma.NotaUpdateManyMutationInput, Prisma.NotaUncheckedUpdateManyInput>
  /**
   * Filter which Notas to update
   */
  where?: Prisma.NotaWhereInput
  /**
   * Limit how many Notas to update.
   */
  limit?: number
}

/**
 * Nota updateManyAndReturn
 */
export type NotaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Nota
   */
  select?: Prisma.NotaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Nota
   */
  omit?: Prisma.NotaOmit<ExtArgs> | null
  /**
   * The data used to update Notas.
   */
  data: Prisma.XOR<Prisma.NotaUpdateManyMutationInput, Prisma.NotaUncheckedUpdateManyInput>
  /**
   * Filter which Notas to update
   */
  where?: Prisma.NotaWhereInput
  /**
   * Limit how many Notas to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotaIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Nota upsert
 */
export type NotaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Nota
   */
  select?: Prisma.NotaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Nota
   */
  omit?: Prisma.NotaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotaInclude<ExtArgs> | null
  /**
   * The filter to search for the Nota to update in case it exists.
   */
  where: Prisma.NotaWhereUniqueInput
  /**
   * In case the Nota found by the `where` argument doesn't exist, create a new Nota with this data.
   */
  create: Prisma.XOR<Prisma.NotaCreateInput, Prisma.NotaUncheckedCreateInput>
  /**
   * In case the Nota was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NotaUpdateInput, Prisma.NotaUncheckedUpdateInput>
}

/**
 * Nota delete
 */
export type NotaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Nota
   */
  select?: Prisma.NotaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Nota
   */
  omit?: Prisma.NotaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotaInclude<ExtArgs> | null
  /**
   * Filter which Nota to delete.
   */
  where: Prisma.NotaWhereUniqueInput
}

/**
 * Nota deleteMany
 */
export type NotaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Notas to delete
   */
  where?: Prisma.NotaWhereInput
  /**
   * Limit how many Notas to delete.
   */
  limit?: number
}

/**
 * Nota.task
 */
export type Nota$taskArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tarea
   */
  select?: Prisma.TareaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tarea
   */
  omit?: Prisma.TareaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TareaInclude<ExtArgs> | null
  where?: Prisma.TareaWhereInput
}

/**
 * Nota without action
 */
export type NotaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Nota
   */
  select?: Prisma.NotaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Nota
   */
  omit?: Prisma.NotaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotaInclude<ExtArgs> | null
}
