
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Proyecto` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Proyecto
 * 
 */
export type ProyectoModel = runtime.Types.Result.DefaultSelection<Prisma.$ProyectoPayload>

export type AggregateProyecto = {
  _count: ProyectoCountAggregateOutputType | null
  _avg: ProyectoAvgAggregateOutputType | null
  _sum: ProyectoSumAggregateOutputType | null
  _min: ProyectoMinAggregateOutputType | null
  _max: ProyectoMaxAggregateOutputType | null
}

export type ProyectoAvgAggregateOutputType = {
  progress: number | null
}

export type ProyectoSumAggregateOutputType = {
  progress: number | null
}

export type ProyectoMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  priority: $Enums.Priority | null
  status: $Enums.Status | null
  progress: number | null
  nextAction: string | null
  createdAt: Date | null
  updatedAt: Date | null
  nextActionTaskId: string | null
  driveFolderId: string | null
}

export type ProyectoMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  priority: $Enums.Priority | null
  status: $Enums.Status | null
  progress: number | null
  nextAction: string | null
  createdAt: Date | null
  updatedAt: Date | null
  nextActionTaskId: string | null
  driveFolderId: string | null
}

export type ProyectoCountAggregateOutputType = {
  id: number
  name: number
  description: number
  priority: number
  status: number
  progress: number
  nextAction: number
  createdAt: number
  updatedAt: number
  nextActionTaskId: number
  driveFolderId: number
  _all: number
}


export type ProyectoAvgAggregateInputType = {
  progress?: true
}

export type ProyectoSumAggregateInputType = {
  progress?: true
}

export type ProyectoMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  priority?: true
  status?: true
  progress?: true
  nextAction?: true
  createdAt?: true
  updatedAt?: true
  nextActionTaskId?: true
  driveFolderId?: true
}

export type ProyectoMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  priority?: true
  status?: true
  progress?: true
  nextAction?: true
  createdAt?: true
  updatedAt?: true
  nextActionTaskId?: true
  driveFolderId?: true
}

export type ProyectoCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  priority?: true
  status?: true
  progress?: true
  nextAction?: true
  createdAt?: true
  updatedAt?: true
  nextActionTaskId?: true
  driveFolderId?: true
  _all?: true
}

export type ProyectoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Proyecto to aggregate.
   */
  where?: Prisma.ProyectoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proyectos to fetch.
   */
  orderBy?: Prisma.ProyectoOrderByWithRelationInput | Prisma.ProyectoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProyectoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proyectos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proyectos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Proyectos
  **/
  _count?: true | ProyectoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProyectoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProyectoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProyectoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProyectoMaxAggregateInputType
}

export type GetProyectoAggregateType<T extends ProyectoAggregateArgs> = {
      [P in keyof T & keyof AggregateProyecto]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProyecto[P]>
    : Prisma.GetScalarType<T[P], AggregateProyecto[P]>
}




export type ProyectoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProyectoWhereInput
  orderBy?: Prisma.ProyectoOrderByWithAggregationInput | Prisma.ProyectoOrderByWithAggregationInput[]
  by: Prisma.ProyectoScalarFieldEnum[] | Prisma.ProyectoScalarFieldEnum
  having?: Prisma.ProyectoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProyectoCountAggregateInputType | true
  _avg?: ProyectoAvgAggregateInputType
  _sum?: ProyectoSumAggregateInputType
  _min?: ProyectoMinAggregateInputType
  _max?: ProyectoMaxAggregateInputType
}

export type ProyectoGroupByOutputType = {
  id: string
  name: string
  description: string | null
  priority: $Enums.Priority
  status: $Enums.Status
  progress: number
  nextAction: string | null
  createdAt: Date
  updatedAt: Date
  nextActionTaskId: string | null
  driveFolderId: string | null
  _count: ProyectoCountAggregateOutputType | null
  _avg: ProyectoAvgAggregateOutputType | null
  _sum: ProyectoSumAggregateOutputType | null
  _min: ProyectoMinAggregateOutputType | null
  _max: ProyectoMaxAggregateOutputType | null
}

export type GetProyectoGroupByPayload<T extends ProyectoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProyectoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProyectoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProyectoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProyectoGroupByOutputType[P]>
      }
    >
  >



export type ProyectoWhereInput = {
  AND?: Prisma.ProyectoWhereInput | Prisma.ProyectoWhereInput[]
  OR?: Prisma.ProyectoWhereInput[]
  NOT?: Prisma.ProyectoWhereInput | Prisma.ProyectoWhereInput[]
  id?: Prisma.StringFilter<"Proyecto"> | string
  name?: Prisma.StringFilter<"Proyecto"> | string
  description?: Prisma.StringNullableFilter<"Proyecto"> | string | null
  priority?: Prisma.EnumPriorityFilter<"Proyecto"> | $Enums.Priority
  status?: Prisma.EnumStatusFilter<"Proyecto"> | $Enums.Status
  progress?: Prisma.IntFilter<"Proyecto"> | number
  nextAction?: Prisma.StringNullableFilter<"Proyecto"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Proyecto"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Proyecto"> | Date | string
  nextActionTaskId?: Prisma.StringNullableFilter<"Proyecto"> | string | null
  driveFolderId?: Prisma.StringNullableFilter<"Proyecto"> | string | null
  tasks?: Prisma.TareaListRelationFilter
  notes?: Prisma.NotaListRelationFilter
  nextActionTask?: Prisma.XOR<Prisma.TareaNullableScalarRelationFilter, Prisma.TareaWhereInput> | null
  archivos?: Prisma.ArchivoListRelationFilter
  templates?: Prisma.DocumentTemplateListRelationFilter
}

export type ProyectoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  priority?: Prisma.SortOrder
  status?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  nextAction?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  nextActionTaskId?: Prisma.SortOrderInput | Prisma.SortOrder
  driveFolderId?: Prisma.SortOrderInput | Prisma.SortOrder
  tasks?: Prisma.TareaOrderByRelationAggregateInput
  notes?: Prisma.NotaOrderByRelationAggregateInput
  nextActionTask?: Prisma.TareaOrderByWithRelationInput
  archivos?: Prisma.ArchivoOrderByRelationAggregateInput
  templates?: Prisma.DocumentTemplateOrderByRelationAggregateInput
}

export type ProyectoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  nextActionTaskId?: string
  AND?: Prisma.ProyectoWhereInput | Prisma.ProyectoWhereInput[]
  OR?: Prisma.ProyectoWhereInput[]
  NOT?: Prisma.ProyectoWhereInput | Prisma.ProyectoWhereInput[]
  name?: Prisma.StringFilter<"Proyecto"> | string
  description?: Prisma.StringNullableFilter<"Proyecto"> | string | null
  priority?: Prisma.EnumPriorityFilter<"Proyecto"> | $Enums.Priority
  status?: Prisma.EnumStatusFilter<"Proyecto"> | $Enums.Status
  progress?: Prisma.IntFilter<"Proyecto"> | number
  nextAction?: Prisma.StringNullableFilter<"Proyecto"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Proyecto"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Proyecto"> | Date | string
  driveFolderId?: Prisma.StringNullableFilter<"Proyecto"> | string | null
  tasks?: Prisma.TareaListRelationFilter
  notes?: Prisma.NotaListRelationFilter
  nextActionTask?: Prisma.XOR<Prisma.TareaNullableScalarRelationFilter, Prisma.TareaWhereInput> | null
  archivos?: Prisma.ArchivoListRelationFilter
  templates?: Prisma.DocumentTemplateListRelationFilter
}, "id" | "nextActionTaskId">

export type ProyectoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  priority?: Prisma.SortOrder
  status?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  nextAction?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  nextActionTaskId?: Prisma.SortOrderInput | Prisma.SortOrder
  driveFolderId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ProyectoCountOrderByAggregateInput
  _avg?: Prisma.ProyectoAvgOrderByAggregateInput
  _max?: Prisma.ProyectoMaxOrderByAggregateInput
  _min?: Prisma.ProyectoMinOrderByAggregateInput
  _sum?: Prisma.ProyectoSumOrderByAggregateInput
}

export type ProyectoScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProyectoScalarWhereWithAggregatesInput | Prisma.ProyectoScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProyectoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProyectoScalarWhereWithAggregatesInput | Prisma.ProyectoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Proyecto"> | string
  name?: Prisma.StringWithAggregatesFilter<"Proyecto"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Proyecto"> | string | null
  priority?: Prisma.EnumPriorityWithAggregatesFilter<"Proyecto"> | $Enums.Priority
  status?: Prisma.EnumStatusWithAggregatesFilter<"Proyecto"> | $Enums.Status
  progress?: Prisma.IntWithAggregatesFilter<"Proyecto"> | number
  nextAction?: Prisma.StringNullableWithAggregatesFilter<"Proyecto"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Proyecto"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Proyecto"> | Date | string
  nextActionTaskId?: Prisma.StringNullableWithAggregatesFilter<"Proyecto"> | string | null
  driveFolderId?: Prisma.StringNullableWithAggregatesFilter<"Proyecto"> | string | null
}

export type ProyectoCreateInput = {
  id?: string
  name: string
  description?: string | null
  priority?: $Enums.Priority
  status?: $Enums.Status
  progress?: number
  nextAction?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  driveFolderId?: string | null
  tasks?: Prisma.TareaCreateNestedManyWithoutProjectInput
  notes?: Prisma.NotaCreateNestedManyWithoutProjectInput
  nextActionTask?: Prisma.TareaCreateNestedOneWithoutIsNextActionForInput
  archivos?: Prisma.ArchivoCreateNestedManyWithoutProjectInput
  templates?: Prisma.DocumentTemplateCreateNestedManyWithoutProjectInput
}

export type ProyectoUncheckedCreateInput = {
  id?: string
  name: string
  description?: string | null
  priority?: $Enums.Priority
  status?: $Enums.Status
  progress?: number
  nextAction?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  nextActionTaskId?: string | null
  driveFolderId?: string | null
  tasks?: Prisma.TareaUncheckedCreateNestedManyWithoutProjectInput
  notes?: Prisma.NotaUncheckedCreateNestedManyWithoutProjectInput
  archivos?: Prisma.ArchivoUncheckedCreateNestedManyWithoutProjectInput
  templates?: Prisma.DocumentTemplateUncheckedCreateNestedManyWithoutProjectInput
}

export type ProyectoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  driveFolderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasks?: Prisma.TareaUpdateManyWithoutProjectNestedInput
  notes?: Prisma.NotaUpdateManyWithoutProjectNestedInput
  nextActionTask?: Prisma.TareaUpdateOneWithoutIsNextActionForNestedInput
  archivos?: Prisma.ArchivoUpdateManyWithoutProjectNestedInput
  templates?: Prisma.DocumentTemplateUpdateManyWithoutProjectNestedInput
}

export type ProyectoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nextActionTaskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driveFolderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasks?: Prisma.TareaUncheckedUpdateManyWithoutProjectNestedInput
  notes?: Prisma.NotaUncheckedUpdateManyWithoutProjectNestedInput
  archivos?: Prisma.ArchivoUncheckedUpdateManyWithoutProjectNestedInput
  templates?: Prisma.DocumentTemplateUncheckedUpdateManyWithoutProjectNestedInput
}

export type ProyectoCreateManyInput = {
  id?: string
  name: string
  description?: string | null
  priority?: $Enums.Priority
  status?: $Enums.Status
  progress?: number
  nextAction?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  nextActionTaskId?: string | null
  driveFolderId?: string | null
}

export type ProyectoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  driveFolderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProyectoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nextActionTaskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driveFolderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ProyectoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  status?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  nextAction?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  nextActionTaskId?: Prisma.SortOrder
  driveFolderId?: Prisma.SortOrder
}

export type ProyectoAvgOrderByAggregateInput = {
  progress?: Prisma.SortOrder
}

export type ProyectoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  status?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  nextAction?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  nextActionTaskId?: Prisma.SortOrder
  driveFolderId?: Prisma.SortOrder
}

export type ProyectoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  status?: Prisma.SortOrder
  progress?: Prisma.SortOrder
  nextAction?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  nextActionTaskId?: Prisma.SortOrder
  driveFolderId?: Prisma.SortOrder
}

export type ProyectoSumOrderByAggregateInput = {
  progress?: Prisma.SortOrder
}

export type ProyectoNullableScalarRelationFilter = {
  is?: Prisma.ProyectoWhereInput | null
  isNot?: Prisma.ProyectoWhereInput | null
}

export type ProyectoScalarRelationFilter = {
  is?: Prisma.ProyectoWhereInput
  isNot?: Prisma.ProyectoWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type EnumPriorityFieldUpdateOperationsInput = {
  set?: $Enums.Priority
}

export type EnumStatusFieldUpdateOperationsInput = {
  set?: $Enums.Status
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type ProyectoCreateNestedOneWithoutTasksInput = {
  create?: Prisma.XOR<Prisma.ProyectoCreateWithoutTasksInput, Prisma.ProyectoUncheckedCreateWithoutTasksInput>
  connectOrCreate?: Prisma.ProyectoCreateOrConnectWithoutTasksInput
  connect?: Prisma.ProyectoWhereUniqueInput
}

export type ProyectoCreateNestedOneWithoutNextActionTaskInput = {
  create?: Prisma.XOR<Prisma.ProyectoCreateWithoutNextActionTaskInput, Prisma.ProyectoUncheckedCreateWithoutNextActionTaskInput>
  connectOrCreate?: Prisma.ProyectoCreateOrConnectWithoutNextActionTaskInput
  connect?: Prisma.ProyectoWhereUniqueInput
}

export type ProyectoUncheckedCreateNestedOneWithoutNextActionTaskInput = {
  create?: Prisma.XOR<Prisma.ProyectoCreateWithoutNextActionTaskInput, Prisma.ProyectoUncheckedCreateWithoutNextActionTaskInput>
  connectOrCreate?: Prisma.ProyectoCreateOrConnectWithoutNextActionTaskInput
  connect?: Prisma.ProyectoWhereUniqueInput
}

export type ProyectoUpdateOneWithoutTasksNestedInput = {
  create?: Prisma.XOR<Prisma.ProyectoCreateWithoutTasksInput, Prisma.ProyectoUncheckedCreateWithoutTasksInput>
  connectOrCreate?: Prisma.ProyectoCreateOrConnectWithoutTasksInput
  upsert?: Prisma.ProyectoUpsertWithoutTasksInput
  disconnect?: Prisma.ProyectoWhereInput | boolean
  delete?: Prisma.ProyectoWhereInput | boolean
  connect?: Prisma.ProyectoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProyectoUpdateToOneWithWhereWithoutTasksInput, Prisma.ProyectoUpdateWithoutTasksInput>, Prisma.ProyectoUncheckedUpdateWithoutTasksInput>
}

export type ProyectoUpdateOneWithoutNextActionTaskNestedInput = {
  create?: Prisma.XOR<Prisma.ProyectoCreateWithoutNextActionTaskInput, Prisma.ProyectoUncheckedCreateWithoutNextActionTaskInput>
  connectOrCreate?: Prisma.ProyectoCreateOrConnectWithoutNextActionTaskInput
  upsert?: Prisma.ProyectoUpsertWithoutNextActionTaskInput
  disconnect?: Prisma.ProyectoWhereInput | boolean
  delete?: Prisma.ProyectoWhereInput | boolean
  connect?: Prisma.ProyectoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProyectoUpdateToOneWithWhereWithoutNextActionTaskInput, Prisma.ProyectoUpdateWithoutNextActionTaskInput>, Prisma.ProyectoUncheckedUpdateWithoutNextActionTaskInput>
}

export type ProyectoUncheckedUpdateOneWithoutNextActionTaskNestedInput = {
  create?: Prisma.XOR<Prisma.ProyectoCreateWithoutNextActionTaskInput, Prisma.ProyectoUncheckedCreateWithoutNextActionTaskInput>
  connectOrCreate?: Prisma.ProyectoCreateOrConnectWithoutNextActionTaskInput
  upsert?: Prisma.ProyectoUpsertWithoutNextActionTaskInput
  disconnect?: Prisma.ProyectoWhereInput | boolean
  delete?: Prisma.ProyectoWhereInput | boolean
  connect?: Prisma.ProyectoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProyectoUpdateToOneWithWhereWithoutNextActionTaskInput, Prisma.ProyectoUpdateWithoutNextActionTaskInput>, Prisma.ProyectoUncheckedUpdateWithoutNextActionTaskInput>
}

export type ProyectoCreateNestedOneWithoutNotesInput = {
  create?: Prisma.XOR<Prisma.ProyectoCreateWithoutNotesInput, Prisma.ProyectoUncheckedCreateWithoutNotesInput>
  connectOrCreate?: Prisma.ProyectoCreateOrConnectWithoutNotesInput
  connect?: Prisma.ProyectoWhereUniqueInput
}

export type ProyectoUpdateOneRequiredWithoutNotesNestedInput = {
  create?: Prisma.XOR<Prisma.ProyectoCreateWithoutNotesInput, Prisma.ProyectoUncheckedCreateWithoutNotesInput>
  connectOrCreate?: Prisma.ProyectoCreateOrConnectWithoutNotesInput
  upsert?: Prisma.ProyectoUpsertWithoutNotesInput
  connect?: Prisma.ProyectoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProyectoUpdateToOneWithWhereWithoutNotesInput, Prisma.ProyectoUpdateWithoutNotesInput>, Prisma.ProyectoUncheckedUpdateWithoutNotesInput>
}

export type ProyectoCreateNestedOneWithoutArchivosInput = {
  create?: Prisma.XOR<Prisma.ProyectoCreateWithoutArchivosInput, Prisma.ProyectoUncheckedCreateWithoutArchivosInput>
  connectOrCreate?: Prisma.ProyectoCreateOrConnectWithoutArchivosInput
  connect?: Prisma.ProyectoWhereUniqueInput
}

export type ProyectoUpdateOneRequiredWithoutArchivosNestedInput = {
  create?: Prisma.XOR<Prisma.ProyectoCreateWithoutArchivosInput, Prisma.ProyectoUncheckedCreateWithoutArchivosInput>
  connectOrCreate?: Prisma.ProyectoCreateOrConnectWithoutArchivosInput
  upsert?: Prisma.ProyectoUpsertWithoutArchivosInput
  connect?: Prisma.ProyectoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProyectoUpdateToOneWithWhereWithoutArchivosInput, Prisma.ProyectoUpdateWithoutArchivosInput>, Prisma.ProyectoUncheckedUpdateWithoutArchivosInput>
}

export type ProyectoCreateNestedOneWithoutTemplatesInput = {
  create?: Prisma.XOR<Prisma.ProyectoCreateWithoutTemplatesInput, Prisma.ProyectoUncheckedCreateWithoutTemplatesInput>
  connectOrCreate?: Prisma.ProyectoCreateOrConnectWithoutTemplatesInput
  connect?: Prisma.ProyectoWhereUniqueInput
}

export type ProyectoUpdateOneWithoutTemplatesNestedInput = {
  create?: Prisma.XOR<Prisma.ProyectoCreateWithoutTemplatesInput, Prisma.ProyectoUncheckedCreateWithoutTemplatesInput>
  connectOrCreate?: Prisma.ProyectoCreateOrConnectWithoutTemplatesInput
  upsert?: Prisma.ProyectoUpsertWithoutTemplatesInput
  disconnect?: Prisma.ProyectoWhereInput | boolean
  delete?: Prisma.ProyectoWhereInput | boolean
  connect?: Prisma.ProyectoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProyectoUpdateToOneWithWhereWithoutTemplatesInput, Prisma.ProyectoUpdateWithoutTemplatesInput>, Prisma.ProyectoUncheckedUpdateWithoutTemplatesInput>
}

export type ProyectoCreateWithoutTasksInput = {
  id?: string
  name: string
  description?: string | null
  priority?: $Enums.Priority
  status?: $Enums.Status
  progress?: number
  nextAction?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  driveFolderId?: string | null
  notes?: Prisma.NotaCreateNestedManyWithoutProjectInput
  nextActionTask?: Prisma.TareaCreateNestedOneWithoutIsNextActionForInput
  archivos?: Prisma.ArchivoCreateNestedManyWithoutProjectInput
  templates?: Prisma.DocumentTemplateCreateNestedManyWithoutProjectInput
}

export type ProyectoUncheckedCreateWithoutTasksInput = {
  id?: string
  name: string
  description?: string | null
  priority?: $Enums.Priority
  status?: $Enums.Status
  progress?: number
  nextAction?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  nextActionTaskId?: string | null
  driveFolderId?: string | null
  notes?: Prisma.NotaUncheckedCreateNestedManyWithoutProjectInput
  archivos?: Prisma.ArchivoUncheckedCreateNestedManyWithoutProjectInput
  templates?: Prisma.DocumentTemplateUncheckedCreateNestedManyWithoutProjectInput
}

export type ProyectoCreateOrConnectWithoutTasksInput = {
  where: Prisma.ProyectoWhereUniqueInput
  create: Prisma.XOR<Prisma.ProyectoCreateWithoutTasksInput, Prisma.ProyectoUncheckedCreateWithoutTasksInput>
}

export type ProyectoCreateWithoutNextActionTaskInput = {
  id?: string
  name: string
  description?: string | null
  priority?: $Enums.Priority
  status?: $Enums.Status
  progress?: number
  nextAction?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  driveFolderId?: string | null
  tasks?: Prisma.TareaCreateNestedManyWithoutProjectInput
  notes?: Prisma.NotaCreateNestedManyWithoutProjectInput
  archivos?: Prisma.ArchivoCreateNestedManyWithoutProjectInput
  templates?: Prisma.DocumentTemplateCreateNestedManyWithoutProjectInput
}

export type ProyectoUncheckedCreateWithoutNextActionTaskInput = {
  id?: string
  name: string
  description?: string | null
  priority?: $Enums.Priority
  status?: $Enums.Status
  progress?: number
  nextAction?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  driveFolderId?: string | null
  tasks?: Prisma.TareaUncheckedCreateNestedManyWithoutProjectInput
  notes?: Prisma.NotaUncheckedCreateNestedManyWithoutProjectInput
  archivos?: Prisma.ArchivoUncheckedCreateNestedManyWithoutProjectInput
  templates?: Prisma.DocumentTemplateUncheckedCreateNestedManyWithoutProjectInput
}

export type ProyectoCreateOrConnectWithoutNextActionTaskInput = {
  where: Prisma.ProyectoWhereUniqueInput
  create: Prisma.XOR<Prisma.ProyectoCreateWithoutNextActionTaskInput, Prisma.ProyectoUncheckedCreateWithoutNextActionTaskInput>
}

export type ProyectoUpsertWithoutTasksInput = {
  update: Prisma.XOR<Prisma.ProyectoUpdateWithoutTasksInput, Prisma.ProyectoUncheckedUpdateWithoutTasksInput>
  create: Prisma.XOR<Prisma.ProyectoCreateWithoutTasksInput, Prisma.ProyectoUncheckedCreateWithoutTasksInput>
  where?: Prisma.ProyectoWhereInput
}

export type ProyectoUpdateToOneWithWhereWithoutTasksInput = {
  where?: Prisma.ProyectoWhereInput
  data: Prisma.XOR<Prisma.ProyectoUpdateWithoutTasksInput, Prisma.ProyectoUncheckedUpdateWithoutTasksInput>
}

export type ProyectoUpdateWithoutTasksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  driveFolderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NotaUpdateManyWithoutProjectNestedInput
  nextActionTask?: Prisma.TareaUpdateOneWithoutIsNextActionForNestedInput
  archivos?: Prisma.ArchivoUpdateManyWithoutProjectNestedInput
  templates?: Prisma.DocumentTemplateUpdateManyWithoutProjectNestedInput
}

export type ProyectoUncheckedUpdateWithoutTasksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nextActionTaskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driveFolderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  notes?: Prisma.NotaUncheckedUpdateManyWithoutProjectNestedInput
  archivos?: Prisma.ArchivoUncheckedUpdateManyWithoutProjectNestedInput
  templates?: Prisma.DocumentTemplateUncheckedUpdateManyWithoutProjectNestedInput
}

export type ProyectoUpsertWithoutNextActionTaskInput = {
  update: Prisma.XOR<Prisma.ProyectoUpdateWithoutNextActionTaskInput, Prisma.ProyectoUncheckedUpdateWithoutNextActionTaskInput>
  create: Prisma.XOR<Prisma.ProyectoCreateWithoutNextActionTaskInput, Prisma.ProyectoUncheckedCreateWithoutNextActionTaskInput>
  where?: Prisma.ProyectoWhereInput
}

export type ProyectoUpdateToOneWithWhereWithoutNextActionTaskInput = {
  where?: Prisma.ProyectoWhereInput
  data: Prisma.XOR<Prisma.ProyectoUpdateWithoutNextActionTaskInput, Prisma.ProyectoUncheckedUpdateWithoutNextActionTaskInput>
}

export type ProyectoUpdateWithoutNextActionTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  driveFolderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasks?: Prisma.TareaUpdateManyWithoutProjectNestedInput
  notes?: Prisma.NotaUpdateManyWithoutProjectNestedInput
  archivos?: Prisma.ArchivoUpdateManyWithoutProjectNestedInput
  templates?: Prisma.DocumentTemplateUpdateManyWithoutProjectNestedInput
}

export type ProyectoUncheckedUpdateWithoutNextActionTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  driveFolderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasks?: Prisma.TareaUncheckedUpdateManyWithoutProjectNestedInput
  notes?: Prisma.NotaUncheckedUpdateManyWithoutProjectNestedInput
  archivos?: Prisma.ArchivoUncheckedUpdateManyWithoutProjectNestedInput
  templates?: Prisma.DocumentTemplateUncheckedUpdateManyWithoutProjectNestedInput
}

export type ProyectoCreateWithoutNotesInput = {
  id?: string
  name: string
  description?: string | null
  priority?: $Enums.Priority
  status?: $Enums.Status
  progress?: number
  nextAction?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  driveFolderId?: string | null
  tasks?: Prisma.TareaCreateNestedManyWithoutProjectInput
  nextActionTask?: Prisma.TareaCreateNestedOneWithoutIsNextActionForInput
  archivos?: Prisma.ArchivoCreateNestedManyWithoutProjectInput
  templates?: Prisma.DocumentTemplateCreateNestedManyWithoutProjectInput
}

export type ProyectoUncheckedCreateWithoutNotesInput = {
  id?: string
  name: string
  description?: string | null
  priority?: $Enums.Priority
  status?: $Enums.Status
  progress?: number
  nextAction?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  nextActionTaskId?: string | null
  driveFolderId?: string | null
  tasks?: Prisma.TareaUncheckedCreateNestedManyWithoutProjectInput
  archivos?: Prisma.ArchivoUncheckedCreateNestedManyWithoutProjectInput
  templates?: Prisma.DocumentTemplateUncheckedCreateNestedManyWithoutProjectInput
}

export type ProyectoCreateOrConnectWithoutNotesInput = {
  where: Prisma.ProyectoWhereUniqueInput
  create: Prisma.XOR<Prisma.ProyectoCreateWithoutNotesInput, Prisma.ProyectoUncheckedCreateWithoutNotesInput>
}

export type ProyectoUpsertWithoutNotesInput = {
  update: Prisma.XOR<Prisma.ProyectoUpdateWithoutNotesInput, Prisma.ProyectoUncheckedUpdateWithoutNotesInput>
  create: Prisma.XOR<Prisma.ProyectoCreateWithoutNotesInput, Prisma.ProyectoUncheckedCreateWithoutNotesInput>
  where?: Prisma.ProyectoWhereInput
}

export type ProyectoUpdateToOneWithWhereWithoutNotesInput = {
  where?: Prisma.ProyectoWhereInput
  data: Prisma.XOR<Prisma.ProyectoUpdateWithoutNotesInput, Prisma.ProyectoUncheckedUpdateWithoutNotesInput>
}

export type ProyectoUpdateWithoutNotesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  driveFolderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasks?: Prisma.TareaUpdateManyWithoutProjectNestedInput
  nextActionTask?: Prisma.TareaUpdateOneWithoutIsNextActionForNestedInput
  archivos?: Prisma.ArchivoUpdateManyWithoutProjectNestedInput
  templates?: Prisma.DocumentTemplateUpdateManyWithoutProjectNestedInput
}

export type ProyectoUncheckedUpdateWithoutNotesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nextActionTaskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driveFolderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasks?: Prisma.TareaUncheckedUpdateManyWithoutProjectNestedInput
  archivos?: Prisma.ArchivoUncheckedUpdateManyWithoutProjectNestedInput
  templates?: Prisma.DocumentTemplateUncheckedUpdateManyWithoutProjectNestedInput
}

export type ProyectoCreateWithoutArchivosInput = {
  id?: string
  name: string
  description?: string | null
  priority?: $Enums.Priority
  status?: $Enums.Status
  progress?: number
  nextAction?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  driveFolderId?: string | null
  tasks?: Prisma.TareaCreateNestedManyWithoutProjectInput
  notes?: Prisma.NotaCreateNestedManyWithoutProjectInput
  nextActionTask?: Prisma.TareaCreateNestedOneWithoutIsNextActionForInput
  templates?: Prisma.DocumentTemplateCreateNestedManyWithoutProjectInput
}

export type ProyectoUncheckedCreateWithoutArchivosInput = {
  id?: string
  name: string
  description?: string | null
  priority?: $Enums.Priority
  status?: $Enums.Status
  progress?: number
  nextAction?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  nextActionTaskId?: string | null
  driveFolderId?: string | null
  tasks?: Prisma.TareaUncheckedCreateNestedManyWithoutProjectInput
  notes?: Prisma.NotaUncheckedCreateNestedManyWithoutProjectInput
  templates?: Prisma.DocumentTemplateUncheckedCreateNestedManyWithoutProjectInput
}

export type ProyectoCreateOrConnectWithoutArchivosInput = {
  where: Prisma.ProyectoWhereUniqueInput
  create: Prisma.XOR<Prisma.ProyectoCreateWithoutArchivosInput, Prisma.ProyectoUncheckedCreateWithoutArchivosInput>
}

export type ProyectoUpsertWithoutArchivosInput = {
  update: Prisma.XOR<Prisma.ProyectoUpdateWithoutArchivosInput, Prisma.ProyectoUncheckedUpdateWithoutArchivosInput>
  create: Prisma.XOR<Prisma.ProyectoCreateWithoutArchivosInput, Prisma.ProyectoUncheckedCreateWithoutArchivosInput>
  where?: Prisma.ProyectoWhereInput
}

export type ProyectoUpdateToOneWithWhereWithoutArchivosInput = {
  where?: Prisma.ProyectoWhereInput
  data: Prisma.XOR<Prisma.ProyectoUpdateWithoutArchivosInput, Prisma.ProyectoUncheckedUpdateWithoutArchivosInput>
}

export type ProyectoUpdateWithoutArchivosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  driveFolderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasks?: Prisma.TareaUpdateManyWithoutProjectNestedInput
  notes?: Prisma.NotaUpdateManyWithoutProjectNestedInput
  nextActionTask?: Prisma.TareaUpdateOneWithoutIsNextActionForNestedInput
  templates?: Prisma.DocumentTemplateUpdateManyWithoutProjectNestedInput
}

export type ProyectoUncheckedUpdateWithoutArchivosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nextActionTaskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driveFolderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasks?: Prisma.TareaUncheckedUpdateManyWithoutProjectNestedInput
  notes?: Prisma.NotaUncheckedUpdateManyWithoutProjectNestedInput
  templates?: Prisma.DocumentTemplateUncheckedUpdateManyWithoutProjectNestedInput
}

export type ProyectoCreateWithoutTemplatesInput = {
  id?: string
  name: string
  description?: string | null
  priority?: $Enums.Priority
  status?: $Enums.Status
  progress?: number
  nextAction?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  driveFolderId?: string | null
  tasks?: Prisma.TareaCreateNestedManyWithoutProjectInput
  notes?: Prisma.NotaCreateNestedManyWithoutProjectInput
  nextActionTask?: Prisma.TareaCreateNestedOneWithoutIsNextActionForInput
  archivos?: Prisma.ArchivoCreateNestedManyWithoutProjectInput
}

export type ProyectoUncheckedCreateWithoutTemplatesInput = {
  id?: string
  name: string
  description?: string | null
  priority?: $Enums.Priority
  status?: $Enums.Status
  progress?: number
  nextAction?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  nextActionTaskId?: string | null
  driveFolderId?: string | null
  tasks?: Prisma.TareaUncheckedCreateNestedManyWithoutProjectInput
  notes?: Prisma.NotaUncheckedCreateNestedManyWithoutProjectInput
  archivos?: Prisma.ArchivoUncheckedCreateNestedManyWithoutProjectInput
}

export type ProyectoCreateOrConnectWithoutTemplatesInput = {
  where: Prisma.ProyectoWhereUniqueInput
  create: Prisma.XOR<Prisma.ProyectoCreateWithoutTemplatesInput, Prisma.ProyectoUncheckedCreateWithoutTemplatesInput>
}

export type ProyectoUpsertWithoutTemplatesInput = {
  update: Prisma.XOR<Prisma.ProyectoUpdateWithoutTemplatesInput, Prisma.ProyectoUncheckedUpdateWithoutTemplatesInput>
  create: Prisma.XOR<Prisma.ProyectoCreateWithoutTemplatesInput, Prisma.ProyectoUncheckedCreateWithoutTemplatesInput>
  where?: Prisma.ProyectoWhereInput
}

export type ProyectoUpdateToOneWithWhereWithoutTemplatesInput = {
  where?: Prisma.ProyectoWhereInput
  data: Prisma.XOR<Prisma.ProyectoUpdateWithoutTemplatesInput, Prisma.ProyectoUncheckedUpdateWithoutTemplatesInput>
}

export type ProyectoUpdateWithoutTemplatesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  driveFolderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasks?: Prisma.TareaUpdateManyWithoutProjectNestedInput
  notes?: Prisma.NotaUpdateManyWithoutProjectNestedInput
  nextActionTask?: Prisma.TareaUpdateOneWithoutIsNextActionForNestedInput
  archivos?: Prisma.ArchivoUpdateManyWithoutProjectNestedInput
}

export type ProyectoUncheckedUpdateWithoutTemplatesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priority?: Prisma.EnumPriorityFieldUpdateOperationsInput | $Enums.Priority
  status?: Prisma.EnumStatusFieldUpdateOperationsInput | $Enums.Status
  progress?: Prisma.IntFieldUpdateOperationsInput | number
  nextAction?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nextActionTaskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  driveFolderId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tasks?: Prisma.TareaUncheckedUpdateManyWithoutProjectNestedInput
  notes?: Prisma.NotaUncheckedUpdateManyWithoutProjectNestedInput
  archivos?: Prisma.ArchivoUncheckedUpdateManyWithoutProjectNestedInput
}


/**
 * Count Type ProyectoCountOutputType
 */

export type ProyectoCountOutputType = {
  tasks: number
  notes: number
  archivos: number
  templates: number
}

export type ProyectoCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tasks?: boolean | ProyectoCountOutputTypeCountTasksArgs
  notes?: boolean | ProyectoCountOutputTypeCountNotesArgs
  archivos?: boolean | ProyectoCountOutputTypeCountArchivosArgs
  templates?: boolean | ProyectoCountOutputTypeCountTemplatesArgs
}

/**
 * ProyectoCountOutputType without action
 */
export type ProyectoCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProyectoCountOutputType
   */
  select?: Prisma.ProyectoCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProyectoCountOutputType without action
 */
export type ProyectoCountOutputTypeCountTasksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TareaWhereInput
}

/**
 * ProyectoCountOutputType without action
 */
export type ProyectoCountOutputTypeCountNotesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NotaWhereInput
}

/**
 * ProyectoCountOutputType without action
 */
export type ProyectoCountOutputTypeCountArchivosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ArchivoWhereInput
}

/**
 * ProyectoCountOutputType without action
 */
export type ProyectoCountOutputTypeCountTemplatesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DocumentTemplateWhereInput
}


export type ProyectoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  priority?: boolean
  status?: boolean
  progress?: boolean
  nextAction?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  nextActionTaskId?: boolean
  driveFolderId?: boolean
  tasks?: boolean | Prisma.Proyecto$tasksArgs<ExtArgs>
  notes?: boolean | Prisma.Proyecto$notesArgs<ExtArgs>
  nextActionTask?: boolean | Prisma.Proyecto$nextActionTaskArgs<ExtArgs>
  archivos?: boolean | Prisma.Proyecto$archivosArgs<ExtArgs>
  templates?: boolean | Prisma.Proyecto$templatesArgs<ExtArgs>
  _count?: boolean | Prisma.ProyectoCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["proyecto"]>

export type ProyectoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  priority?: boolean
  status?: boolean
  progress?: boolean
  nextAction?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  nextActionTaskId?: boolean
  driveFolderId?: boolean
  nextActionTask?: boolean | Prisma.Proyecto$nextActionTaskArgs<ExtArgs>
}, ExtArgs["result"]["proyecto"]>

export type ProyectoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  priority?: boolean
  status?: boolean
  progress?: boolean
  nextAction?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  nextActionTaskId?: boolean
  driveFolderId?: boolean
  nextActionTask?: boolean | Prisma.Proyecto$nextActionTaskArgs<ExtArgs>
}, ExtArgs["result"]["proyecto"]>

export type ProyectoSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  priority?: boolean
  status?: boolean
  progress?: boolean
  nextAction?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  nextActionTaskId?: boolean
  driveFolderId?: boolean
}

export type ProyectoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "priority" | "status" | "progress" | "nextAction" | "createdAt" | "updatedAt" | "nextActionTaskId" | "driveFolderId", ExtArgs["result"]["proyecto"]>
export type ProyectoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tasks?: boolean | Prisma.Proyecto$tasksArgs<ExtArgs>
  notes?: boolean | Prisma.Proyecto$notesArgs<ExtArgs>
  nextActionTask?: boolean | Prisma.Proyecto$nextActionTaskArgs<ExtArgs>
  archivos?: boolean | Prisma.Proyecto$archivosArgs<ExtArgs>
  templates?: boolean | Prisma.Proyecto$templatesArgs<ExtArgs>
  _count?: boolean | Prisma.ProyectoCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProyectoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  nextActionTask?: boolean | Prisma.Proyecto$nextActionTaskArgs<ExtArgs>
}
export type ProyectoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  nextActionTask?: boolean | Prisma.Proyecto$nextActionTaskArgs<ExtArgs>
}

export type $ProyectoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Proyecto"
  objects: {
    tasks: Prisma.$TareaPayload<ExtArgs>[]
    notes: Prisma.$NotaPayload<ExtArgs>[]
    nextActionTask: Prisma.$TareaPayload<ExtArgs> | null
    archivos: Prisma.$ArchivoPayload<ExtArgs>[]
    templates: Prisma.$DocumentTemplatePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string | null
    priority: $Enums.Priority
    status: $Enums.Status
    progress: number
    nextAction: string | null
    createdAt: Date
    updatedAt: Date
    nextActionTaskId: string | null
    driveFolderId: string | null
  }, ExtArgs["result"]["proyecto"]>
  composites: {}
}

export type ProyectoGetPayload<S extends boolean | null | undefined | ProyectoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProyectoPayload, S>

export type ProyectoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProyectoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProyectoCountAggregateInputType | true
  }

export interface ProyectoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Proyecto'], meta: { name: 'Proyecto' } }
  /**
   * Find zero or one Proyecto that matches the filter.
   * @param {ProyectoFindUniqueArgs} args - Arguments to find a Proyecto
   * @example
   * // Get one Proyecto
   * const proyecto = await prisma.proyecto.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProyectoFindUniqueArgs>(args: Prisma.SelectSubset<T, ProyectoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProyectoClient<runtime.Types.Result.GetResult<Prisma.$ProyectoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Proyecto that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProyectoFindUniqueOrThrowArgs} args - Arguments to find a Proyecto
   * @example
   * // Get one Proyecto
   * const proyecto = await prisma.proyecto.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProyectoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProyectoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProyectoClient<runtime.Types.Result.GetResult<Prisma.$ProyectoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Proyecto that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProyectoFindFirstArgs} args - Arguments to find a Proyecto
   * @example
   * // Get one Proyecto
   * const proyecto = await prisma.proyecto.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProyectoFindFirstArgs>(args?: Prisma.SelectSubset<T, ProyectoFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProyectoClient<runtime.Types.Result.GetResult<Prisma.$ProyectoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Proyecto that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProyectoFindFirstOrThrowArgs} args - Arguments to find a Proyecto
   * @example
   * // Get one Proyecto
   * const proyecto = await prisma.proyecto.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProyectoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProyectoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProyectoClient<runtime.Types.Result.GetResult<Prisma.$ProyectoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Proyectos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProyectoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Proyectos
   * const proyectos = await prisma.proyecto.findMany()
   * 
   * // Get first 10 Proyectos
   * const proyectos = await prisma.proyecto.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const proyectoWithIdOnly = await prisma.proyecto.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProyectoFindManyArgs>(args?: Prisma.SelectSubset<T, ProyectoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProyectoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Proyecto.
   * @param {ProyectoCreateArgs} args - Arguments to create a Proyecto.
   * @example
   * // Create one Proyecto
   * const Proyecto = await prisma.proyecto.create({
   *   data: {
   *     // ... data to create a Proyecto
   *   }
   * })
   * 
   */
  create<T extends ProyectoCreateArgs>(args: Prisma.SelectSubset<T, ProyectoCreateArgs<ExtArgs>>): Prisma.Prisma__ProyectoClient<runtime.Types.Result.GetResult<Prisma.$ProyectoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Proyectos.
   * @param {ProyectoCreateManyArgs} args - Arguments to create many Proyectos.
   * @example
   * // Create many Proyectos
   * const proyecto = await prisma.proyecto.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProyectoCreateManyArgs>(args?: Prisma.SelectSubset<T, ProyectoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Proyectos and returns the data saved in the database.
   * @param {ProyectoCreateManyAndReturnArgs} args - Arguments to create many Proyectos.
   * @example
   * // Create many Proyectos
   * const proyecto = await prisma.proyecto.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Proyectos and only return the `id`
   * const proyectoWithIdOnly = await prisma.proyecto.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProyectoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProyectoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProyectoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Proyecto.
   * @param {ProyectoDeleteArgs} args - Arguments to delete one Proyecto.
   * @example
   * // Delete one Proyecto
   * const Proyecto = await prisma.proyecto.delete({
   *   where: {
   *     // ... filter to delete one Proyecto
   *   }
   * })
   * 
   */
  delete<T extends ProyectoDeleteArgs>(args: Prisma.SelectSubset<T, ProyectoDeleteArgs<ExtArgs>>): Prisma.Prisma__ProyectoClient<runtime.Types.Result.GetResult<Prisma.$ProyectoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Proyecto.
   * @param {ProyectoUpdateArgs} args - Arguments to update one Proyecto.
   * @example
   * // Update one Proyecto
   * const proyecto = await prisma.proyecto.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProyectoUpdateArgs>(args: Prisma.SelectSubset<T, ProyectoUpdateArgs<ExtArgs>>): Prisma.Prisma__ProyectoClient<runtime.Types.Result.GetResult<Prisma.$ProyectoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Proyectos.
   * @param {ProyectoDeleteManyArgs} args - Arguments to filter Proyectos to delete.
   * @example
   * // Delete a few Proyectos
   * const { count } = await prisma.proyecto.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProyectoDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProyectoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Proyectos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProyectoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Proyectos
   * const proyecto = await prisma.proyecto.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProyectoUpdateManyArgs>(args: Prisma.SelectSubset<T, ProyectoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Proyectos and returns the data updated in the database.
   * @param {ProyectoUpdateManyAndReturnArgs} args - Arguments to update many Proyectos.
   * @example
   * // Update many Proyectos
   * const proyecto = await prisma.proyecto.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Proyectos and only return the `id`
   * const proyectoWithIdOnly = await prisma.proyecto.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProyectoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProyectoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProyectoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Proyecto.
   * @param {ProyectoUpsertArgs} args - Arguments to update or create a Proyecto.
   * @example
   * // Update or create a Proyecto
   * const proyecto = await prisma.proyecto.upsert({
   *   create: {
   *     // ... data to create a Proyecto
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Proyecto we want to update
   *   }
   * })
   */
  upsert<T extends ProyectoUpsertArgs>(args: Prisma.SelectSubset<T, ProyectoUpsertArgs<ExtArgs>>): Prisma.Prisma__ProyectoClient<runtime.Types.Result.GetResult<Prisma.$ProyectoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Proyectos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProyectoCountArgs} args - Arguments to filter Proyectos to count.
   * @example
   * // Count the number of Proyectos
   * const count = await prisma.proyecto.count({
   *   where: {
   *     // ... the filter for the Proyectos we want to count
   *   }
   * })
  **/
  count<T extends ProyectoCountArgs>(
    args?: Prisma.Subset<T, ProyectoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProyectoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Proyecto.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProyectoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProyectoAggregateArgs>(args: Prisma.Subset<T, ProyectoAggregateArgs>): Prisma.PrismaPromise<GetProyectoAggregateType<T>>

  /**
   * Group by Proyecto.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProyectoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProyectoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProyectoGroupByArgs['orderBy'] }
      : { orderBy?: ProyectoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProyectoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProyectoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Proyecto model
 */
readonly fields: ProyectoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Proyecto.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProyectoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tasks<T extends Prisma.Proyecto$tasksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Proyecto$tasksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TareaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  notes<T extends Prisma.Proyecto$notesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Proyecto$notesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NotaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  nextActionTask<T extends Prisma.Proyecto$nextActionTaskArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Proyecto$nextActionTaskArgs<ExtArgs>>): Prisma.Prisma__TareaClient<runtime.Types.Result.GetResult<Prisma.$TareaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  archivos<T extends Prisma.Proyecto$archivosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Proyecto$archivosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ArchivoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  templates<T extends Prisma.Proyecto$templatesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Proyecto$templatesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocumentTemplatePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Proyecto model
 */
export interface ProyectoFieldRefs {
  readonly id: Prisma.FieldRef<"Proyecto", 'String'>
  readonly name: Prisma.FieldRef<"Proyecto", 'String'>
  readonly description: Prisma.FieldRef<"Proyecto", 'String'>
  readonly priority: Prisma.FieldRef<"Proyecto", 'Priority'>
  readonly status: Prisma.FieldRef<"Proyecto", 'Status'>
  readonly progress: Prisma.FieldRef<"Proyecto", 'Int'>
  readonly nextAction: Prisma.FieldRef<"Proyecto", 'String'>
  readonly createdAt: Prisma.FieldRef<"Proyecto", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Proyecto", 'DateTime'>
  readonly nextActionTaskId: Prisma.FieldRef<"Proyecto", 'String'>
  readonly driveFolderId: Prisma.FieldRef<"Proyecto", 'String'>
}
    

// Custom InputTypes
/**
 * Proyecto findUnique
 */
export type ProyectoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proyecto
   */
  select?: Prisma.ProyectoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proyecto
   */
  omit?: Prisma.ProyectoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProyectoInclude<ExtArgs> | null
  /**
   * Filter, which Proyecto to fetch.
   */
  where: Prisma.ProyectoWhereUniqueInput
}

/**
 * Proyecto findUniqueOrThrow
 */
export type ProyectoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proyecto
   */
  select?: Prisma.ProyectoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proyecto
   */
  omit?: Prisma.ProyectoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProyectoInclude<ExtArgs> | null
  /**
   * Filter, which Proyecto to fetch.
   */
  where: Prisma.ProyectoWhereUniqueInput
}

/**
 * Proyecto findFirst
 */
export type ProyectoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proyecto
   */
  select?: Prisma.ProyectoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proyecto
   */
  omit?: Prisma.ProyectoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProyectoInclude<ExtArgs> | null
  /**
   * Filter, which Proyecto to fetch.
   */
  where?: Prisma.ProyectoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proyectos to fetch.
   */
  orderBy?: Prisma.ProyectoOrderByWithRelationInput | Prisma.ProyectoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Proyectos.
   */
  cursor?: Prisma.ProyectoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proyectos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proyectos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Proyectos.
   */
  distinct?: Prisma.ProyectoScalarFieldEnum | Prisma.ProyectoScalarFieldEnum[]
}

/**
 * Proyecto findFirstOrThrow
 */
export type ProyectoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proyecto
   */
  select?: Prisma.ProyectoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proyecto
   */
  omit?: Prisma.ProyectoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProyectoInclude<ExtArgs> | null
  /**
   * Filter, which Proyecto to fetch.
   */
  where?: Prisma.ProyectoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proyectos to fetch.
   */
  orderBy?: Prisma.ProyectoOrderByWithRelationInput | Prisma.ProyectoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Proyectos.
   */
  cursor?: Prisma.ProyectoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proyectos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proyectos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Proyectos.
   */
  distinct?: Prisma.ProyectoScalarFieldEnum | Prisma.ProyectoScalarFieldEnum[]
}

/**
 * Proyecto findMany
 */
export type ProyectoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proyecto
   */
  select?: Prisma.ProyectoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proyecto
   */
  omit?: Prisma.ProyectoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProyectoInclude<ExtArgs> | null
  /**
   * Filter, which Proyectos to fetch.
   */
  where?: Prisma.ProyectoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proyectos to fetch.
   */
  orderBy?: Prisma.ProyectoOrderByWithRelationInput | Prisma.ProyectoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Proyectos.
   */
  cursor?: Prisma.ProyectoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proyectos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proyectos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Proyectos.
   */
  distinct?: Prisma.ProyectoScalarFieldEnum | Prisma.ProyectoScalarFieldEnum[]
}

/**
 * Proyecto create
 */
export type ProyectoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proyecto
   */
  select?: Prisma.ProyectoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proyecto
   */
  omit?: Prisma.ProyectoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProyectoInclude<ExtArgs> | null
  /**
   * The data needed to create a Proyecto.
   */
  data: Prisma.XOR<Prisma.ProyectoCreateInput, Prisma.ProyectoUncheckedCreateInput>
}

/**
 * Proyecto createMany
 */
export type ProyectoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Proyectos.
   */
  data: Prisma.ProyectoCreateManyInput | Prisma.ProyectoCreateManyInput[]
}

/**
 * Proyecto createManyAndReturn
 */
export type ProyectoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proyecto
   */
  select?: Prisma.ProyectoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Proyecto
   */
  omit?: Prisma.ProyectoOmit<ExtArgs> | null
  /**
   * The data used to create many Proyectos.
   */
  data: Prisma.ProyectoCreateManyInput | Prisma.ProyectoCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProyectoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Proyecto update
 */
export type ProyectoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proyecto
   */
  select?: Prisma.ProyectoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proyecto
   */
  omit?: Prisma.ProyectoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProyectoInclude<ExtArgs> | null
  /**
   * The data needed to update a Proyecto.
   */
  data: Prisma.XOR<Prisma.ProyectoUpdateInput, Prisma.ProyectoUncheckedUpdateInput>
  /**
   * Choose, which Proyecto to update.
   */
  where: Prisma.ProyectoWhereUniqueInput
}

/**
 * Proyecto updateMany
 */
export type ProyectoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Proyectos.
   */
  data: Prisma.XOR<Prisma.ProyectoUpdateManyMutationInput, Prisma.ProyectoUncheckedUpdateManyInput>
  /**
   * Filter which Proyectos to update
   */
  where?: Prisma.ProyectoWhereInput
  /**
   * Limit how many Proyectos to update.
   */
  limit?: number
}

/**
 * Proyecto updateManyAndReturn
 */
export type ProyectoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proyecto
   */
  select?: Prisma.ProyectoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Proyecto
   */
  omit?: Prisma.ProyectoOmit<ExtArgs> | null
  /**
   * The data used to update Proyectos.
   */
  data: Prisma.XOR<Prisma.ProyectoUpdateManyMutationInput, Prisma.ProyectoUncheckedUpdateManyInput>
  /**
   * Filter which Proyectos to update
   */
  where?: Prisma.ProyectoWhereInput
  /**
   * Limit how many Proyectos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProyectoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Proyecto upsert
 */
export type ProyectoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proyecto
   */
  select?: Prisma.ProyectoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proyecto
   */
  omit?: Prisma.ProyectoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProyectoInclude<ExtArgs> | null
  /**
   * The filter to search for the Proyecto to update in case it exists.
   */
  where: Prisma.ProyectoWhereUniqueInput
  /**
   * In case the Proyecto found by the `where` argument doesn't exist, create a new Proyecto with this data.
   */
  create: Prisma.XOR<Prisma.ProyectoCreateInput, Prisma.ProyectoUncheckedCreateInput>
  /**
   * In case the Proyecto was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProyectoUpdateInput, Prisma.ProyectoUncheckedUpdateInput>
}

/**
 * Proyecto delete
 */
export type ProyectoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proyecto
   */
  select?: Prisma.ProyectoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proyecto
   */
  omit?: Prisma.ProyectoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProyectoInclude<ExtArgs> | null
  /**
   * Filter which Proyecto to delete.
   */
  where: Prisma.ProyectoWhereUniqueInput
}

/**
 * Proyecto deleteMany
 */
export type ProyectoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Proyectos to delete
   */
  where?: Prisma.ProyectoWhereInput
  /**
   * Limit how many Proyectos to delete.
   */
  limit?: number
}

/**
 * Proyecto.tasks
 */
export type Proyecto$tasksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tarea
   */
  select?: Prisma.TareaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tarea
   */
  omit?: Prisma.TareaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TareaInclude<ExtArgs> | null
  where?: Prisma.TareaWhereInput
  orderBy?: Prisma.TareaOrderByWithRelationInput | Prisma.TareaOrderByWithRelationInput[]
  cursor?: Prisma.TareaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TareaScalarFieldEnum | Prisma.TareaScalarFieldEnum[]
}

/**
 * Proyecto.notes
 */
export type Proyecto$notesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Nota
   */
  select?: Prisma.NotaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Nota
   */
  omit?: Prisma.NotaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NotaInclude<ExtArgs> | null
  where?: Prisma.NotaWhereInput
  orderBy?: Prisma.NotaOrderByWithRelationInput | Prisma.NotaOrderByWithRelationInput[]
  cursor?: Prisma.NotaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.NotaScalarFieldEnum | Prisma.NotaScalarFieldEnum[]
}

/**
 * Proyecto.nextActionTask
 */
export type Proyecto$nextActionTaskArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tarea
   */
  select?: Prisma.TareaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tarea
   */
  omit?: Prisma.TareaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TareaInclude<ExtArgs> | null
  where?: Prisma.TareaWhereInput
}

/**
 * Proyecto.archivos
 */
export type Proyecto$archivosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Archivo
   */
  select?: Prisma.ArchivoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Archivo
   */
  omit?: Prisma.ArchivoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ArchivoInclude<ExtArgs> | null
  where?: Prisma.ArchivoWhereInput
  orderBy?: Prisma.ArchivoOrderByWithRelationInput | Prisma.ArchivoOrderByWithRelationInput[]
  cursor?: Prisma.ArchivoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ArchivoScalarFieldEnum | Prisma.ArchivoScalarFieldEnum[]
}

/**
 * Proyecto.templates
 */
export type Proyecto$templatesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentTemplate
   */
  select?: Prisma.DocumentTemplateSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentTemplate
   */
  omit?: Prisma.DocumentTemplateOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentTemplateInclude<ExtArgs> | null
  where?: Prisma.DocumentTemplateWhereInput
  orderBy?: Prisma.DocumentTemplateOrderByWithRelationInput | Prisma.DocumentTemplateOrderByWithRelationInput[]
  cursor?: Prisma.DocumentTemplateWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DocumentTemplateScalarFieldEnum | Prisma.DocumentTemplateScalarFieldEnum[]
}

/**
 * Proyecto without action
 */
export type ProyectoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proyecto
   */
  select?: Prisma.ProyectoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proyecto
   */
  omit?: Prisma.ProyectoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProyectoInclude<ExtArgs> | null
}
