
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ArchivoKind = {
  NOTE: 'NOTE',
  FILE: 'FILE'
} as const

export type ArchivoKind = (typeof ArchivoKind)[keyof typeof ArchivoKind]


export const Priority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
} as const

export type Priority = (typeof Priority)[keyof typeof Priority]


export const Status = {
  PLANNING: 'PLANNING',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED'
} as const

export type Status = (typeof Status)[keyof typeof Status]


export const TareaStatus = {
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING: 'WAITING',
  DONE: 'DONE'
} as const

export type TareaStatus = (typeof TareaStatus)[keyof typeof TareaStatus]
