
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Proyecto'
export type * from './models/Tarea'
export type * from './models/Nota'
export type * from './models/Archivo'
export type * from './models/GoogleDriveToken'
export type * from './commonInputTypes'